package com.example.vokabeltrainer

import com.example.vokabeltrainer.Vocabulary_cl_5.unit_1


object VocabularyData {

    val unit_2 = listOf(
        VocabularyEntry(germanWords = listOf("Regel"), englishWords = listOf("rule")),
        VocabularyEntry(germanWords = listOf("Handbuch", "Kalender"), englishWords = listOf("planner")),
        VocabularyEntry(germanWords = listOf("Mittagessen"), englishWords = listOf("lunch")),
        VocabularyEntry(germanWords = listOf("Cafeteria"), englishWords = listOf("cafeteria")),
        VocabularyEntry(germanWords = listOf("Geld"), englishWords = listOf("money")),
        VocabularyEntry(germanWords = listOf("Automat", "Maschine", "Apparat", "Gerät"), englishWords = listOf("machine")),
        VocabularyEntry(germanWords = listOf("bezahlen"), englishWords = listOf("to pay (for)")),
        VocabularyEntry(germanWords = listOf("Finger"), englishWords = listOf("finger")),
        VocabularyEntry(germanWords = listOf("Kunstunterricht"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("kaufen"), englishWords = listOf("to buy")),
        VocabularyEntry(germanWords = listOf("Süßigkeiten", "Bonbons"), englishWords = listOf("sweets")),
        VocabularyEntry(germanWords = listOf("Geschäft", "Laden"), englishWords = listOf("shop")),
        VocabularyEntry(germanWords = listOf("Füller"), englishWords = listOf("pen")),
        VocabularyEntry(germanWords = listOf("Bleistift", "Buntstift"), englishWords = listOf("pencil")),
        VocabularyEntry(germanWords = listOf("Federmappchen", "Mäppchen"), englishWords = listOf("pencil-case")),
        VocabularyEntry(germanWords = listOf("Übungsheft"), englishWords = listOf("exercise book")),
        VocabularyEntry(germanWords = listOf("Lineal"), englishWords = listOf("ruler")),
        VocabularyEntry(germanWords = listOf("Radiergummi"), englishWords = listOf("rubber")),
        VocabularyEntry(germanWords = listOf("Uniform"), englishWords = listOf("uniform")),
        VocabularyEntry(germanWords = listOf("Aufnahmestudie", "Tonstudio"), englishWords = listOf("recording studio")),
        VocabularyEntry(germanWords = listOf("Klassenlehrer-in"), englishWords = listOf("tutor")),
        VocabularyEntry(germanWords = listOf("Klassenzimmer"), englishWords = listOf("classroom")),
        VocabularyEntry(germanWords = listOf("Klassenkamerad-in", "Mitschüler-in"), englishWords = listOf("classmates")),
        VocabularyEntry(germanWords = listOf("besitzen", "haben"), englishWords = listOf("to have", "to have got")),
        VocabularyEntry(germanWords = listOf("Frage"), englishWords = listOf("question")),
        VocabularyEntry(germanWords = listOf("heute"), englishWords = listOf("today")),
        VocabularyEntry(germanWords = listOf("Schultasche"), englishWords = listOf("schoolbag")),
        VocabularyEntry(germanWords = listOf("Klasse", "Tutoriumsgruppe"), englishWords = listOf("tutor group")),
        VocabularyEntry(germanWords = listOf("Guten Morgen"), englishWords = listOf("Good morning")),
        VocabularyEntry(germanWords = listOf("jeder", "alle"), englishWords = listOf("everyone")),
        VocabularyEntry(germanWords = listOf("Schüler", "Schülerin", "Student", "Studentin"), englishWords = listOf("student")),
        VocabularyEntry(germanWords = listOf("nennen"), englishWords = listOf("to call")),
        VocabularyEntry(germanWords = listOf("ihn", "ihm"), englishWords = listOf("him")),
        VocabularyEntry(germanWords = listOf("kein", "keine"), englishWords = listOf("no")),
        VocabularyEntry(germanWords = listOf("Ich singe und tanze gerne"), englishWords = listOf("I like singing and dancing")),
        VocabularyEntry(germanWords = listOf("singen"), englishWords = listOf("to sing")),
        VocabularyEntry(germanWords = listOf("tanzen"), englishWords = listOf("to dance")),
        VocabularyEntry(germanWords = listOf("Projekt"), englishWords = listOf("project")),
        VocabularyEntry(germanWords = listOf("tja", "nun"), englishWords = listOf("well")),
        VocabularyEntry(germanWords = listOf("etwas"), englishWords = listOf("something")),
        VocabularyEntry(germanWords = listOf("Warte ab"), englishWords = listOf("Wait and see")),
        VocabularyEntry(germanWords = listOf("Lehrer", "Lehrerin"), englishWords = listOf("teacher")),
        VocabularyEntry(germanWords = listOf("Tafel"), englishWords = listOf("board")),
        VocabularyEntry(germanWords = listOf("Gruppe", "Klasse"), englishWords = listOf("group")),
        VocabularyEntry(germanWords = listOf("viele", "jede Menge"), englishWords = listOf("lots of")),
        VocabularyEntry(germanWords = listOf("Büro"), englishWords = listOf("office")),
        VocabularyEntry(germanWords = listOf("Großeltern"), englishWords = listOf("grandparents")),
        VocabularyEntry(germanWords = listOf("Talentwettbewerb"), englishWords = listOf("talent show")),
        VocabularyEntry(germanWords = listOf("schicken", "senden"), englishWords = listOf("to send")),
        VocabularyEntry(germanWords = listOf("Essen", "Lebensmittel"), englishWords = listOf("food")),
        VocabularyEntry(germanWords = listOf("Karotte", "Möhre"), englishWords = listOf("carrot")),
        VocabularyEntry(germanWords = listOf("Pudding", "Nachtisch"), englishWords = listOf("pudding")),
        VocabularyEntry(germanWords = listOf("Restaurant", "Gaststätte"), englishWords = listOf("restaurant")),
        VocabularyEntry(germanWords = listOf("Taschengeld"), englishWords = listOf("pocket money")),
        VocabularyEntry(germanWords = listOf("benutzen", "verwenden", "gebrauchen"), englishWords = listOf("to use")),
        VocabularyEntry(germanWords = listOf("Bitte schön", "Hier sind Sie", "Hier bist du"), englishWords = listOf("here you are")),
        VocabularyEntry(germanWords = listOf("sei höflich", "seid höflich"), englishWords = listOf("be polite")),
        VocabularyEntry(germanWords = listOf("wessen"), englishWords = listOf("whose")),
        VocabularyEntry(germanWords = listOf("Deutsche Schüler haben Glück"), englishWords = listOf("German students are lucky")),
        VocabularyEntry(germanWords = listOf("Unterrichtsstunde", "Schulstunde", "Unterricht"), englishWords = listOf("lesson")),
        VocabularyEntry(germanWords = listOf("Gebäude"), englishWords = listOf("building")),
        VocabularyEntry(germanWords = listOf("Kunst"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("Englisch"), englishWords = listOf("English")),
        VocabularyEntry(germanWords = listOf("Deutsch"), englishWords = listOf("German")),
        VocabularyEntry(germanWords = listOf("Erdkunde", "Geografie"), englishWords = listOf("Geography")),
        VocabularyEntry(germanWords = listOf("Mathematik", "Mathe"), englishWords = listOf("Maths")),
        VocabularyEntry(germanWords = listOf("Naturwissenschaften"), englishWords = listOf("Science")),
        VocabularyEntry(germanWords = listOf("Musik"), englishWords = listOf("Music")),
        VocabularyEntry(germanWords = listOf("Latein"), englishWords = listOf("Latin")),
        VocabularyEntry(germanWords = listOf("Französisch"), englishWords = listOf("French")),
        VocabularyEntry(germanWords = listOf("Geschichte"), englishWords = listOf("History")),
        VocabularyEntry(germanWords = listOf("Sport"), englishWords = listOf("PE", "Physical Education")),
        VocabularyEntry(germanWords = listOf("Religion"), englishWords = listOf("RE", "Religious Education")),
        VocabularyEntry(germanWords = listOf("starren", "anstarren"), englishWords = listOf("to stare")),
        VocabularyEntry(germanWords = listOf("lustig", "witzig"), englishWords = listOf("funny")),
        VocabularyEntry(germanWords = listOf("Mittagspause"), englishWords = listOf("the lunch break")),
        VocabularyEntry(germanWords = listOf("sie", "ihnen"), englishWords = listOf("them")),
        VocabularyEntry(germanWords = listOf("vergessen"), englishWords = listOf("to forget")),
        VocabularyEntry(germanWords = listOf("machen", "tun"), englishWords = listOf("to do")),
        VocabularyEntry(germanWords = listOf("lustig", "fröhlich"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in", "in...hinein"), englishWords = listOf("into")),
        VocabularyEntry(germanWords = listOf("allein", "ohne fremde Hilfe"), englishWords = listOf("alone")),
        VocabularyEntry(germanWords = listOf("bringen", "mitbringen"), englishWords = listOf("to bring")),
        VocabularyEntry(germanWords = listOf("zu spät sein", "zu spät kommen"), englishWords = listOf("to be late")),
        VocabularyEntry(germanWords = listOf("sein"), englishWords = listOf("to be")),
        VocabularyEntry(germanWords = listOf("anhaben", "tragen"), englishWords = listOf("to wear")),
        VocabularyEntry(germanWords = listOf("rennen", "laufen"), englishWords = listOf("to run")),
        VocabularyEntry(germanWords = listOf("Hausaufgaben"), englishWords = listOf("homework")),
        VocabularyEntry(germanWords = listOf("unhöflich", "unverschämt"), englishWords = listOf("rude")),
        VocabularyEntry(germanWords = listOf("sitzen"), englishWords = listOf("to sit")),
        VocabularyEntry(germanWords = listOf("anschauen", "ansehen"), englishWords = listOf("to look at")),
        VocabularyEntry(germanWords = listOf("wenn", "wann", "als"), englishWords = listOf("when")),
        VocabularyEntry(germanWords = listOf("schon", "bereits"), englishWords = listOf("already")),
        VocabularyEntry(germanWords = listOf("hinzufügen", "ergänzen"), englishWords = listOf("to add")),
        VocabularyEntry(germanWords = listOf("Pommes frites"), englishWords = listOf("chips")),
        VocabularyEntry(germanWords = listOf("Ende", "Schluss"), englishWords = listOf("end")),
        VocabularyEntry(germanWords = listOf("da drüben", "dort drüben"), englishWords = listOf("over there")),
        VocabularyEntry(germanWords = listOf("diese (hier)"), englishWords = listOf("these")),
        VocabularyEntry(germanWords = listOf("jene", "die dort"), englishWords = listOf("those")),
        VocabularyEntry(germanWords = listOf("finden", "herausfinden"), englishWords = listOf("to find")),
        VocabularyEntry(germanWords = listOf("jemandem einen Streich spielen"), englishWords = listOf("to play a trick on")),
        VocabularyEntry(germanWords = listOf("Woche"), englishWords = listOf("week")),
        VocabularyEntry(germanWords = listOf("vor", "bevor"), englishWords = listOf("before")),
        VocabularyEntry(germanWords = listOf("arbeiten"), englishWords = listOf("to work")),
        VocabularyEntry(germanWords = listOf("Paar"), englishWords = listOf("pair")),
        VocabularyEntry(germanWords = listOf("Präsentation", "Vortrag"), englishWords = listOf("presentation")),
        VocabularyEntry(germanWords = listOf("Aufnahme", "Aufzeichnung"), englishWords = listOf("recording")),
        VocabularyEntry(germanWords = listOf("Gedicht"), englishWords = listOf("poem")),
        VocabularyEntry(germanWords = listOf("sicher"), englishWords = listOf("sure")),
        VocabularyEntry(germanWords = listOf("Stimme"), englishWords = listOf("voice")),
        VocabularyEntry(germanWords = listOf("nächste", "nächster", "nächstes", "der Nächste", "die Nächste"), englishWords = listOf("next")),
        VocabularyEntry(germanWords = listOf("eifersüchtig sein (auf)", "neidisch sein (auf)"), englishWords = listOf("to be jealous (of)")),
        VocabularyEntry(germanWords = listOf("beliebt", "populär"), englishWords = listOf("popular")),
        VocabularyEntry(germanWords = listOf("König"), englishWords = listOf("king")),
        VocabularyEntry(germanWords = listOf("Klasse"), englishWords = listOf("class")),
        VocabularyEntry(germanWords = listOf("Komm schon!", "Komm jetzt!"), englishWords = listOf("Come on!")),
        VocabularyEntry(germanWords = listOf("Ein paar Minuten später"), englishWords = listOf("A few minutes later")),
        VocabularyEntry(germanWords = listOf("Ich höre...", "Ich habe gehört, dass..."), englishWords = listOf("I hear...")),
        VocabularyEntry(germanWords = listOf("gerade", "nur", "einfach"), englishWords = listOf("just")),
        VocabularyEntry(germanWords = listOf("Witz"), englishWords = listOf("joke")),
        VocabularyEntry(germanWords = listOf("wirklich"), englishWords = listOf("really")),
        VocabularyEntry(germanWords = listOf("viel"), englishWords = listOf("much")),
        VocabularyEntry(germanWords = listOf("Zeit"), englishWords = listOf("time")),
        VocabularyEntry(germanWords = listOf("kennen", "wissen"), englishWords = listOf("to know")),
        VocabularyEntry(germanWords = listOf("Du bist dran"), englishWords = listOf("It's your turn")),
        VocabularyEntry(germanWords = listOf("Mach das aus!", "Macht das aus!", "Hör auf!", "Hört auf!"), englishWords = listOf("Stop it!")),
        VocabularyEntry(germanWords = listOf("lachen"), englishWords = listOf("to laugh")),
        VocabularyEntry(germanWords = listOf("wütend", "zornig", "verärgert", "böse"), englishWords = listOf("angry")),
        VocabularyEntry(germanWords = listOf("geben", "schenken"), englishWords = listOf("to give")),
        VocabularyEntry(germanWords = listOf("denken", "nachdenken"), englishWords = listOf("to think")),
        VocabularyEntry(germanWords = listOf("Ärger machen", "in Schwierigkeiten bringen"), englishWords = listOf("to make trouble")),
        VocabularyEntry(germanWords = listOf("Er hat recht."), englishWords = listOf("He's right.")),
        VocabularyEntry(germanWords = listOf("Story", "Geschichte", "Erzählung"), englishWords = listOf("story", "stories")),
        VocabularyEntry(germanWords = listOf("weil", "da"), englishWords = listOf("because"))
    )

    val unit_3 = listOf(
        VocabularyEntry(germanWords = listOf("Käse"), englishWords = listOf("cheese")),
        VocabularyEntry(germanWords = listOf("vormittags (Uhrzeit)"), englishWords = listOf("a.m.")),
        VocabularyEntry(germanWords = listOf("nachmittags (Uhrzeit)", "abends (Uhrzeit)"), englishWords = listOf("p.m.")),
        VocabularyEntry(germanWords = listOf("Überraschung"), englishWords = listOf("surprise")),
        VocabularyEntry(germanWords = listOf("Koch-AG"), englishWords = listOf("Cooking Club")),
        VocabularyEntry(germanWords = listOf("Verein", "Klub", "AG"), englishWords = listOf("club")),
        VocabularyEntry(germanWords = listOf("mit dem Fahrrad"), englishWords = listOf("by bike")),
        VocabularyEntry(germanWords = listOf("sich hinsetzen", "sich setzen"), englishWords = listOf("to sit down")),
        VocabularyEntry(germanWords = listOf("frühstücken"), englishWords = listOf("to have breakfast")),
        VocabularyEntry(germanWords = listOf("Es ist Zeit aufzustehen!"), englishWords = listOf("Time to get up!")),
        VocabularyEntry(germanWords = listOf("aufräumen", "in Ordnung bringen"), englishWords = listOf("to tidy")),
        VocabularyEntry(germanWords = listOf("so machst du..."), englishWords = listOf("this is how you (do)")),
        VocabularyEntry(germanWords = listOf("schlafen"), englishWords = listOf("to sleep")),
        VocabularyEntry(germanWords = listOf("ins Bett gehen"), englishWords = listOf("to go to bed"))
    )

    val combinedList = unit_1 + unit_2 + unit_3

    val allLists: Map<String, List<VocabularyEntry>> = mapOf(
        "Wiederholung (alle Vokabeln)" to combinedList,
        "Unit 1" to unit_1,
        "Unit 2" to unit_2,
        "Unit 3" to unit_3

    )

    // Standardmäßig ausgewählte Liste oder null, wenn keine Vorauswahl getroffen werden soll
    var currentListName: String? = allLists.keys.firstOrNull() // Wählt die erste Liste als Standard

    fun getCurrentVocabularyList(): List<VocabularyEntry>? {
        return currentListName?.let { allLists[it] }
    }
}