package com.example.vokabeltrainer

import com.example.vokabeltrainer.Vocabulary_cl_5.unit_1


object VocabularyData {

    val unit_2 = listOf(
        VocabularyEntry(germanWords = listOf("Regel"), englishWords = listOf("rule")),
        VocabularyEntry(germanWords = listOf("Handbuch", "Kalender"), englishWords = listOf("planner")),
        VocabularyEntry(germanWords = listOf("Mittagessen"), englishWords = listOf("lunch")),
        VocabularyEntry(germanWords = listOf("Cafeteria"), englishWords = listOf("cafeteria")),
        VocabularyEntry(germanWords = listOf("Geld"), englishWords = listOf("money")),
        VocabularyEntry(germanWords = listOf("Automat", "Maschine", "Apparat", "Gerät"), englishWords = listOf("machine")),
        VocabularyEntry(germanWords = listOf("bezahlen"), englishWords = listOf("to pay (for)")),
        VocabularyEntry(germanWords = listOf("Finger"), englishWords = listOf("finger")),
        VocabularyEntry(germanWords = listOf("Kunstunterricht"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("kaufen"), englishWords = listOf("to buy")),
        VocabularyEntry(germanWords = listOf("Süßigkeiten", "Bonbons"), englishWords = listOf("sweets")),
        VocabularyEntry(germanWords = listOf("Geschäft", "Laden"), englishWords = listOf("shop")),
        VocabularyEntry(germanWords = listOf("Füller"), englishWords = listOf("pen")),
        VocabularyEntry(germanWords = listOf("Bleistift", "Buntstift"), englishWords = listOf("pencil")),
        VocabularyEntry(germanWords = listOf("Federmappchen", "Mäppchen"), englishWords = listOf("pencil-case")),
        VocabularyEntry(germanWords = listOf("Übungsheft"), englishWords = listOf("exercise book")),
        VocabularyEntry(germanWords = listOf("Lineal"), englishWords = listOf("ruler")),
        VocabularyEntry(germanWords = listOf("Radiergummi"), englishWords = listOf("rubber")),
        VocabularyEntry(germanWords = listOf("Uniform"), englishWords = listOf("uniform")),
        VocabularyEntry(germanWords = listOf("Aufnahmestudie", "Tonstudio"), englishWords = listOf("recording studio")),
        VocabularyEntry(germanWords = listOf("Klassenlehrer-in"), englishWords = listOf("tutor")),
        VocabularyEntry(germanWords = listOf("Klassenzimmer"), englishWords = listOf("classroom")),
        VocabularyEntry(germanWords = listOf("Klassenkamerad-in", "Mitschüler-in"), englishWords = listOf("classmates")),
        VocabularyEntry(germanWords = listOf("besitzen", "haben"), englishWords = listOf("to have", "to have got")),
        VocabularyEntry(germanWords = listOf("Frage"), englishWords = listOf("question")),
        VocabularyEntry(germanWords = listOf("heute"), englishWords = listOf("today")),
        VocabularyEntry(germanWords = listOf("Schultasche"), englishWords = listOf("schoolbag")),
        VocabularyEntry(germanWords = listOf("Klasse", "Tutoriumsgruppe"), englishWords = listOf("tutor group")),
        VocabularyEntry(germanWords = listOf("Guten Morgen"), englishWords = listOf("Good morning")),
        VocabularyEntry(germanWords = listOf("jeder", "alle"), englishWords = listOf("everyone")),
        VocabularyEntry(germanWords = listOf("Schüler", "Schülerin", "Student", "Studentin"), englishWords = listOf("student")),
        VocabularyEntry(germanWords = listOf("nennen"), englishWords = listOf("to call")),
        VocabularyEntry(germanWords = listOf("ihn", "ihm"), englishWords = listOf("him")),
        VocabularyEntry(germanWords = listOf("kein", "keine"), englishWords = listOf("no")),
        VocabularyEntry(germanWords = listOf("Ich singe und tanze gerne"), englishWords = listOf("I like singing and dancing")),
        VocabularyEntry(germanWords = listOf("singen"), englishWords = listOf("to sing")),
        VocabularyEntry(germanWords = listOf("tanzen"), englishWords = listOf("to dance")),
        VocabularyEntry(germanWords = listOf("Projekt"), englishWords = listOf("project")),
        VocabularyEntry(germanWords = listOf("tja", "nun"), englishWords = listOf("well")),
        VocabularyEntry(germanWords = listOf("etwas"), englishWords = listOf("something")),
        VocabularyEntry(germanWords = listOf("Warte ab"), englishWords = listOf("Wait and see")),
        VocabularyEntry(germanWords = listOf("Lehrer", "Lehrerin"), englishWords = listOf("teacher")),
        VocabularyEntry(germanWords = listOf("Tafel"), englishWords = listOf("board")),
        VocabularyEntry(germanWords = listOf("Gruppe", "Klasse"), englishWords = listOf("group")),
        VocabularyEntry(germanWords = listOf("viele", "jede Menge"), englishWords = listOf("lots of")),
        VocabularyEntry(germanWords = listOf("Büro"), englishWords = listOf("office")),
        VocabularyEntry(germanWords = listOf("Großeltern"), englishWords = listOf("grandparents")),
        VocabularyEntry(germanWords = listOf("Talentwettbewerb"), englishWords = listOf("talent show")),
        VocabularyEntry(germanWords = listOf("schicken", "senden"), englishWords = listOf("to send")),
        VocabularyEntry(germanWords = listOf("Essen", "Lebensmittel"), englishWords = listOf("food")),
        VocabularyEntry(germanWords = listOf("Karotte", "Möhre"), englishWords = listOf("carrot")),
        VocabularyEntry(germanWords = listOf("Pudding", "Nachtisch"), englishWords = listOf("pudding")),
        VocabularyEntry(germanWords = listOf("Restaurant", "Gaststätte"), englishWords = listOf("restaurant")),
        VocabularyEntry(germanWords = listOf("Taschengeld"), englishWords = listOf("pocket money")),
        VocabularyEntry(germanWords = listOf("benutzen", "verwenden", "gebrauchen"), englishWords = listOf("to use")),
        VocabularyEntry(germanWords = listOf("Bitte schön", "Hier sind Sie", "Hier bist du"), englishWords = listOf("here you are")),
        VocabularyEntry(germanWords = listOf("sei höflich", "seid höflich"), englishWords = listOf("be polite")),
        VocabularyEntry(germanWords = listOf("wessen"), englishWords = listOf("whose")),
        VocabularyEntry(germanWords = listOf("Deutsche Schüler haben Glück"), englishWords = listOf("German students are lucky")),
        VocabularyEntry(germanWords = listOf("Unterrichtsstunde", "Schulstunde", "Unterricht"), englishWords = listOf("lesson")),
        VocabularyEntry(germanWords = listOf("Gebäude"), englishWords = listOf("building")),
        VocabularyEntry(germanWords = listOf("Kunst"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("Englisch"), englishWords = listOf("English")),
        VocabularyEntry(germanWords = listOf("Deutsch"), englishWords = listOf("German")),
        VocabularyEntry(germanWords = listOf("Erdkunde", "Geografie"), englishWords = listOf("Geography")),
        VocabularyEntry(germanWords = listOf("Mathematik", "Mathe"), englishWords = listOf("Maths")),
        VocabularyEntry(germanWords = listOf("Naturwissenschaften"), englishWords = listOf("Science")),
        VocabularyEntry(germanWords = listOf("Musik"), englishWords = listOf("Music")),
        VocabularyEntry(germanWords = listOf("Latein"), englishWords = listOf("Latin")),
        VocabularyEntry(germanWords = listOf("Französisch"), englishWords = listOf("French")),
        VocabularyEntry(germanWords = listOf("Geschichte"), englishWords = listOf("History")),
        VocabularyEntry(germanWords = listOf("Sport"), englishWords = listOf("PE", "Physical Education")),
        VocabularyEntry(germanWords = listOf("Religion"), englishWords = listOf("RE", "Religious Education")),
        VocabularyEntry(germanWords = listOf("starren", "anstarren"), englishWords = listOf("to stare")),
        VocabularyEntry(germanWords = listOf("lustig", "witzig"), englishWords = listOf("funny")),
        VocabularyEntry(germanWords = listOf("Mittagspause"), englishWords = listOf("the lunch break")),
        VocabularyEntry(germanWords = listOf("sie", "ihnen"), englishWords = listOf("them")),
        VocabularyEntry(germanWords = listOf("vergessen"), englishWords = listOf("to forget")),
        VocabularyEntry(germanWords = listOf("machen", "tun"), englishWords = listOf("to do")),
        VocabularyEntry(germanWords = listOf("lustig", "fröhlich"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in", "in...hinein"), englishWords = listOf("into")),
        VocabularyEntry(germanWords = listOf("allein", "ohne fremde Hilfe"), englishWords = listOf("alone")),
        VocabularyEntry(germanWords = listOf("bringen", "mitbringen"), englishWords = listOf("to bring")),
        VocabularyEntry(germanWords = listOf("zu spät sein", "zu spät kommen"), englishWords = listOf("to be late")),
        VocabularyEntry(germanWords = listOf("sein"), englishWords = listOf("to be")),
        VocabularyEntry(germanWords = listOf("anhaben", "tragen"), englishWords = listOf("to wear")),
        VocabularyEntry(germanWords = listOf("rennen", "laufen"), englishWords = listOf("to run")),
        VocabularyEntry(germanWords = listOf("Hausaufgaben"), englishWords = listOf("homework")),
        VocabularyEntry(germanWords = listOf("unhöflich", "unverschämt"), englishWords = listOf("rude")),
        VocabularyEntry(germanWords = listOf("sitzen"), englishWords = listOf("to sit")),
        VocabularyEntry(germanWords = listOf("anschauen", "ansehen"), englishWords = listOf("to look at")),
        VocabularyEntry(germanWords = listOf("wenn", "wann", "als"), englishWords = listOf("when")),
        VocabularyEntry(germanWords = listOf("schon", "bereits"), englishWords = listOf("already")),
        VocabularyEntry(germanWords = listOf("hinzufügen", "ergänzen"), englishWords = listOf("to add")),
        VocabularyEntry(germanWords = listOf("Pommes frites"), englishWords = listOf("chips")),
        VocabularyEntry(germanWords = listOf("Ende", "Schluss"), englishWords = listOf("end")),
        VocabularyEntry(germanWords = listOf("da drüben", "dort drüben"), englishWords = listOf("over there")),
        VocabularyEntry(germanWords = listOf("diese (hier)"), englishWords = listOf("these")),
        VocabularyEntry(germanWords = listOf("jene", "die dort"), englishWords = listOf("those")),
        VocabularyEntry(germanWords = listOf("finden", "herausfinden"), englishWords = listOf("to find")),
        VocabularyEntry(germanWords = listOf("jemandem einen Streich spielen"), englishWords = listOf("to play a trick on")),
        VocabularyEntry(germanWords = listOf("Woche"), englishWords = listOf("week")),
        VocabularyEntry(germanWords = listOf("vor", "bevor"), englishWords = listOf("before")),
        VocabularyEntry(germanWords = listOf("arbeiten"), englishWords = listOf("to work")),
        VocabularyEntry(germanWords = listOf("Paar"), englishWords = listOf("pair")),
        VocabularyEntry(germanWords = listOf("Präsentation", "Vortrag"), englishWords = listOf("presentation")),
        VocabularyEntry(germanWords = listOf("Aufnahme", "Aufzeichnung"), englishWords = listOf("recording")),
        VocabularyEntry(germanWords = listOf("Gedicht"), englishWords = listOf("poem")),
        VocabularyEntry(germanWords = listOf("sicher"), englishWords = listOf("sure")),
        VocabularyEntry(germanWords = listOf("Stimme"), englishWords = listOf("voice")),
        VocabularyEntry(germanWords = listOf("nächste", "nächster", "nächstes", "der Nächste", "die Nächste"), englishWords = listOf("next")),
        VocabularyEntry(germanWords = listOf("eifersüchtig sein (auf)", "neidisch sein (auf)"), englishWords = listOf("to be jealous (of)")),
        VocabularyEntry(germanWords = listOf("beliebt", "populär"), englishWords = listOf("popular")),
        VocabularyEntry(germanWords = listOf("König"), englishWords = listOf("king")),
        VocabularyEntry(germanWords = listOf("Klasse"), englishWords = listOf("class")),
        VocabularyEntry(germanWords = listOf("Komm schon!", "Komm jetzt!"), englishWords = listOf("Come on!")),
        VocabularyEntry(germanWords = listOf("Ein paar Minuten später"), englishWords = listOf("A few minutes later")),
        VocabularyEntry(germanWords = listOf("Ich höre...", "Ich habe gehört, dass..."), englishWords = listOf("I hear...")),
        VocabularyEntry(germanWords = listOf("gerade", "nur", "einfach"), englishWords = listOf("just")),
        VocabularyEntry(germanWords = listOf("Witz"), englishWords = listOf("joke")),
        VocabularyEntry(germanWords = listOf("wirklich"), englishWords = listOf("really")),
        VocabularyEntry(germanWords = listOf("viel"), englishWords = listOf("much")),
        VocabularyEntry(germanWords = listOf("Zeit"), englishWords = listOf("time")),
        VocabularyEntry(germanWords = listOf("kennen", "wissen"), englishWords = listOf("to know")),
        VocabularyEntry(germanWords = listOf("Du bist dran"), englishWords = listOf("It's your turn")),
        VocabularyEntry(germanWords = listOf("Mach das aus!", "Macht das aus!", "Hör auf!", "Hört auf!"), englishWords = listOf("Stop it!")),
        VocabularyEntry(germanWords = listOf("lachen"), englishWords = listOf("to laugh")),
        VocabularyEntry(germanWords = listOf("wütend", "zornig", "verärgert", "böse"), englishWords = listOf("angry")),
        VocabularyEntry(germanWords = listOf("geben", "schenken"), englishWords = listOf("to give")),
        VocabularyEntry(germanWords = listOf("denken", "nachdenken"), englishWords = listOf("to think")),
        VocabularyEntry(germanWords = listOf("Ärger machen", "in Schwierigkeiten bringen"), englishWords = listOf("to make trouble")),
        VocabularyEntry(germanWords = listOf("Er hat recht."), englishWords = listOf("He's right.")),
        VocabularyEntry(germanWords = listOf("Story", "Geschichte", "Erzählung"), englishWords = listOf("story", "stories")),
        VocabularyEntry(germanWords = listOf("weil", "da"), englishWords = listOf("because"))
    )

    val unit_3 = listOf(
        VocabularyEntry(germanWords = listOf("Käse"), englishWords = listOf("cheese")),
        VocabularyEntry(germanWords = listOf("vormittags (Uhrzeit)"), englishWords = listOf("a.m.")),
        VocabularyEntry(germanWords = listOf("nachmittags (Uhrzeit)", "abends (Uhrzeit)"), englishWords = listOf("p.m.")),
        VocabularyEntry(germanWords = listOf("Überraschung"), englishWords = listOf("surprise")),
        VocabularyEntry(germanWords = listOf("Koch-AG"), englishWords = listOf("Cooking Club")),
        VocabularyEntry(germanWords = listOf("Verein", "Klub", "AG"), englishWords = listOf("club")),
        VocabularyEntry(germanWords = listOf("mit dem Fahrrad"), englishWords = listOf("by bike")),
        VocabularyEntry(germanWords = listOf("sich hinsetzen", "sich setzen"), englishWords = listOf("to sit down")),
        VocabularyEntry(germanWords = listOf("frühstücken"), englishWords = listOf("to have breakfast")),
        VocabularyEntry(germanWords = listOf("Es ist Zeit aufzustehen!"), englishWords = listOf("Time to get up!")),
        VocabularyEntry(germanWords = listOf("aufräumen", "in Ordnung bringen"), englishWords = listOf("to tidy")),
        VocabularyEntry(germanWords = listOf("so machst du..."), englishWords = listOf("this is how you (do)")),
        VocabularyEntry(germanWords = listOf("schlafen"), englishWords = listOf("to sleep")),
        VocabularyEntry(germanWords = listOf("ins Bett gehen"), englishWords = listOf("to go to bed")),
        VocabularyEntry(germanWords = listOf("aufräumen", "in Ordnung bringen"), englishWords = listOf("to tidy")),
        VocabularyEntry(germanWords = listOf("so machst du..."), englishWords = listOf("this is how you (do)")),
        VocabularyEntry(germanWords = listOf("schlafen"), englishWords = listOf("to sleep")),
        VocabularyEntry(germanWords = listOf("ins Bett gehen"), englishWords = listOf("to go to bed")),
        VocabularyEntry(germanWords = listOf("Wie spät ist es?", "Wie viel Uhr ist es?"), englishWords = listOf("What's the time?")),
        VocabularyEntry(germanWords = listOf("jede", "jeder", "jedes"), englishWords = listOf("every")),
        VocabularyEntry(germanWords = listOf("kommen"), englishWords = listOf("to come")),
        VocabularyEntry(germanWords = listOf("nach Hause"), englishWords = listOf("home")),
        VocabularyEntry(germanWords = listOf("Abendessen"), englishWords = listOf("dinner")),
        VocabularyEntry(germanWords = listOf("um halb acht"), englishWords = listOf("at 7:30")),
        VocabularyEntry(germanWords = listOf("dann", "danach"), englishWords = listOf("then")),
        VocabularyEntry(germanWords = listOf("nie", "niemals"), englishWords = listOf("never")),
        VocabularyEntry(germanWords = listOf("Morgen", "Vormittag"), englishWords = listOf("morning")),
        VocabularyEntry(germanWords = listOf("Stiefmutter"), englishWords = listOf("stepmum")),
        VocabularyEntry(germanWords = listOf("wenn", "falls", "ob"), englishWords = listOf("if")),
        VocabularyEntry(germanWords = listOf("bis"), englishWords = listOf("till")),
        VocabularyEntry(germanWords = listOf("danach"), englishWords = listOf("after that")),
        VocabularyEntry(germanWords = listOf("montags"), englishWords = listOf("on Mondays")),
        VocabularyEntry(germanWords = listOf("Korbball"), englishWords = listOf("netball")),
        VocabularyEntry(germanWords = listOf("anders", "andere/-r/-s", "weitere"), englishWords = listOf("other")),
        VocabularyEntry(germanWords = listOf("sofort gleich"), englishWords = listOf("right away")),
        VocabularyEntry(germanWords = listOf("oft", "häufig"), englishWords = listOf("often")),
        VocabularyEntry(germanWords = listOf("Abend"), englishWords = listOf("evening")),
        VocabularyEntry(germanWords = listOf("manchmal"), englishWords = listOf("sometimes")),
        VocabularyEntry(germanWords = listOf("normalerweise", "gewöhnlich", "meistens"), englishWords = listOf("usually")),
        VocabularyEntry(germanWords = listOf("lang"), englishWords = listOf("long")),
        VocabularyEntry(germanWords = listOf("Ich bin hundemüde"), englishWords = listOf("I'm dog-tired")),
        VocabularyEntry(germanWords = listOf("müde"), englishWords = listOf("tired")),
        VocabularyEntry(germanWords = listOf("Wie wäre es mit...?", "Was ist mit...?"), englishWords = listOf("What about...?")),
        VocabularyEntry(germanWords = listOf("Nachmittag"), englishWords = listOf("afternoon")),
        VocabularyEntry(germanWords = listOf("suchen nach"), englishWords = listOf("to look for")),
        VocabularyEntry(germanWords = listOf("schnarchen"), englishWords = listOf("snore")),
        VocabularyEntry(germanWords = listOf("Zimmergenosse", "Zimmergenossin"), englishWords = listOf("roommate")),
        VocabularyEntry(germanWords = listOf("Trainer", "Trainerin"), englishWords = listOf("coach")),
        VocabularyEntry(germanWords = listOf("Letzte", "Letzter", "Letztes"), englishWords = listOf("last")),
        VocabularyEntry(germanWords = listOf("morgen"), englishWords = listOf("tomorrow")),
        VocabularyEntry(germanWords = listOf("Sie geht mir auf die Nerven"), englishWords = listOf("She gets on my nerves")),
        VocabularyEntry(germanWords = listOf("Oma"), englishWords = listOf("granny")),
        VocabularyEntry(germanWords = listOf("aufpassen auf", "hüten", "sich kümmern um"), englishWords = listOf("to look after")),
        VocabularyEntry(germanWords = listOf("fragen", "bitten"), englishWords = listOf("to ask")),
        VocabularyEntry(germanWords = listOf("sprechen", "reden"), englishWords = listOf("to talk")),
        VocabularyEntry(germanWords = listOf("aufhören (mit)", "anhalten", "stoppen"), englishWords = listOf("to stop")),
        VocabularyEntry(germanWords = listOf("plaudern", "chatten (sich online unterhalten)"), englishWords = listOf("to chat")),
        VocabularyEntry(germanWords = listOf("sogar", "selbst"), englishWords = listOf("even")),
        VocabularyEntry(germanWords = listOf("Arbeit"), englishWords = listOf("work")),
        VocabularyEntry(germanWords = listOf("Tierarzt", "Tierärztin"), englishWords = listOf("vet")),
        VocabularyEntry(germanWords = listOf("Nachbar", "Nachbarin"), englishWords = listOf("neighbour")),
        VocabularyEntry(germanWords = listOf("nehmen", "mitnehmen", "wegnehmen", "bringen", "mitbringen"), englishWords = listOf("(to) take")),
        VocabularyEntry(germanWords = listOf("Haustier"), englishWords = listOf("pet")),
        VocabularyEntry(germanWords = listOf("Arztpraxis", "Praxis", "Praxisräume"), englishWords = listOf("surgery")),
        VocabularyEntry(germanWords = listOf("warum"), englishWords = listOf("why")),
        VocabularyEntry(germanWords = listOf("Vorsicht!", "Pass auf!", "Passt auf!"), englishWords = listOf("Be careful")),
        VocabularyEntry(germanWords = listOf("Fehler"), englishWords = listOf("mistake")),
        VocabularyEntry(germanWords = listOf("Kochen"), englishWords = listOf("cooking")),
        VocabularyEntry(germanWords = listOf("Dialog", "Gespräch"), englishWords = listOf("dialogue")),
        VocabularyEntry(germanWords = listOf("Redner", "Rednerin", "Sprecher", "Sprecherin"), englishWords = listOf("speaker")),
        VocabularyEntry(germanWords = listOf("Worum geht es in...?", "Worum geht es im...?"), englishWords = listOf("What is... about?")),
        VocabularyEntry(germanWords = listOf("gehen um", "handeln von"), englishWords = listOf("to be about")),
        VocabularyEntry(germanWords = listOf("herausfinden"), englishWords = listOf("to find out")),
        VocabularyEntry(germanWords = listOf("Situation"), englishWords = listOf("situation")),
        VocabularyEntry(germanWords = listOf("sich verbessern", "verbessern"), englishWords = listOf("(to) improve")),
        VocabularyEntry(germanWords = listOf("aufwärmen", "sich aufwärmen"), englishWords = listOf("(to) warm up")),
        VocabularyEntry(germanWords = listOf("Mund"), englishWords = listOf("mouth")),
        VocabularyEntry(germanWords = listOf("Ton", "Geräusch", "Klang"), englishWords = listOf("sound")),
        VocabularyEntry(germanWords = listOf("in Form kommen", "fit werden"), englishWords = listOf("(to) get fit")),
        VocabularyEntry(germanWords = listOf("Rhythmus"), englishWords = listOf("rhythm")),
        VocabularyEntry(germanWords = listOf("aufstehen (von einer Sitzgelegenheit)"), englishWords = listOf("(to) stand up")),
        VocabularyEntry(germanWords = listOf("Klatsche in die Hände", "Klatscht in die Hände"), englishWords = listOf("Clap your hands.")),
        VocabularyEntry(germanWords = listOf("laut"), englishWords = listOf("loud")),
        VocabularyEntry(germanWords = listOf("sehr"), englishWords = listOf("very much")),
        VocabularyEntry(germanWords = listOf("sprechen"), englishWords = listOf("(to) speak")),
        VocabularyEntry(germanWords = listOf("klar", "deutlich"), englishWords = listOf("clear")),
        VocabularyEntry(germanWords = listOf("eine Theaterszene spielen"), englishWords = listOf("acting a scene")),
        VocabularyEntry(germanWords = listOf("waschen", "sich waschen"), englishWords = listOf("(to) wash")),
        VocabularyEntry(germanWords = listOf("Gesicht"), englishWords = listOf("face")),
        VocabularyEntry(germanWords = listOf("machen", "tun", "bilden"), englishWords = listOf("(to) make")),
        VocabularyEntry(germanWords = listOf("früh"), englishWords = listOf("early")),
        VocabularyEntry(germanWords = listOf("auf Wiedersehen"), englishWords = listOf("goodbye")),
        VocabularyEntry(germanWords = listOf("bellen"), englishWords = listOf("(to) bark")),
        VocabularyEntry(germanWords = listOf("Angst haben (vor)"), englishWords = listOf("(to) be scared (of)")),
        VocabularyEntry(germanWords = listOf("wegrennen"), englishWords = listOf("(to) run away")),
        VocabularyEntry(germanWords = listOf("Spaß haben", "sich amüsieren"), englishWords = listOf("(to) have fun")),
        VocabularyEntry(germanWords = listOf("horchen auf"), englishWords = listOf("(to) listen for")),
        VocabularyEntry(germanWords = listOf("Sitz! (Befehl für Hunde)"), englishWords = listOf("Sit!")),
        VocabularyEntry(germanWords = listOf("um... herum", "umher"), englishWords = listOf("around")),
        VocabularyEntry(germanWords = listOf("Schwanz", "Schweif"), englishWords = listOf("tail")),
        VocabularyEntry(germanWords = listOf("viel zu lernen"), englishWords = listOf("a lot to learn")),
        VocabularyEntry(germanWords = listOf("setzen", "stellen", "legen"), englishWords = listOf("(to) put")),
        VocabularyEntry(germanWords = listOf("Getränk"), englishWords = listOf("drink")),
        VocabularyEntry(germanWords = listOf("hinfallen", "umkippen"), englishWords = listOf("(to) fall over")),
        VocabularyEntry(germanWords = listOf("werfen (nach)"), englishWords = listOf("(to) throw (at)")),
        VocabularyEntry(germanWords = listOf("Schuh"), englishWords = listOf("shoe")),
        VocabularyEntry(germanWords = listOf("einschlafen"), englishWords = listOf("(to) fall asleep")),
        VocabularyEntry(germanWords = listOf("jagen", "nachjagen"), englishWords = listOf("(to) chase")),
        VocabularyEntry(germanWords = listOf("Gesicht"), englishWords = listOf("face")),
        VocabularyEntry(germanWords = listOf("Mund"), englishWords = listOf("mouth")),
        VocabularyEntry(germanWords = listOf("Auge"), englishWords = listOf("eye")),
        VocabularyEntry(germanWords = listOf("Ohr"), englishWords = listOf("ear")),
        VocabularyEntry(germanWords = listOf("Nase"), englishWords = listOf("nose")),
        VocabularyEntry(germanWords = listOf("Kopf"), englishWords = listOf("head")),
        VocabularyEntry(germanWords = listOf("Haar", "Haare"), englishWords = listOf("hair")),
        VocabularyEntry(germanWords = listOf("Hand"), englishWords = listOf("hand")),
        VocabularyEntry(germanWords = listOf("Arm"), englishWords = listOf("arm")),
        VocabularyEntry(germanWords = listOf("Schulter"), englishWords = listOf("shoulder")),
        VocabularyEntry(germanWords = listOf("Fuß"), englishWords = listOf("foot", "feet (pl)")),
        VocabularyEntry(germanWords = listOf("Bein"), englishWords = listOf("leg")),
        VocabularyEntry(germanWords = listOf("Zeh"), englishWords = listOf("toe")),
        VocabularyEntry(germanWords = listOf("Wie man..."), englishWords = listOf("How to...")),
        VocabularyEntry(germanWords = listOf("besichtigen", "besuchen"), englishWords = listOf("(to) visit")),
        VocabularyEntry(germanWords = listOf("wichtig"), englishWords = listOf("important")),
        VocabularyEntry(germanWords = listOf("Seite"), englishWords = listOf("page")),
        VocabularyEntry(germanWords = listOf("was man..."), englishWords = listOf("what to...")),
        VocabularyEntry(germanWords = listOf("englischsprachig"), englishWords = listOf("English-speaking")),
        VocabularyEntry(germanWords = listOf("Lächeln"), englishWords = listOf("smile")),
        VocabularyEntry(germanWords = listOf("Entschuldigung!", "Entschuldigen Sie!"), englishWords = listOf("Excuse me")),
        VocabularyEntry(germanWords = listOf("natürlich", "selbstverständlich"), englishWords = listOf("of course")),
        VocabularyEntry(germanWords = listOf("(ein Bonbon) nehmen", "(ein Bonbon) essen"), englishWords = listOf("(to) have (a sweet)")),
        VocabularyEntry(germanWords = listOf("Bitte schön!", "Nichts zu danken!", "Gern geschehen"), englishWords = listOf("You're welcome")),
        VocabularyEntry(germanWords = listOf("Weg", "Art und Weise"), englishWords = listOf("way")),
        VocabularyEntry(germanWords = listOf("Limonade"), englishWords = listOf("Lemonade")),
        VocabularyEntry(germanWords = listOf("Stundenplan", "Fahrplan"), englishWords = listOf("timetable")),
        VocabularyEntry(germanWords = listOf("im Weg sein", "im Weg stehen"), englishWords = listOf("(to) be in the way")),
        VocabularyEntry(germanWords = listOf("Busbahnhof"), englishWords = listOf("bus station")),
        VocabularyEntry(germanWords = listOf("Person", "Mensch"), englishWords = listOf("person", "people (pl.)")),
        VocabularyEntry(germanWords = listOf("Box", "Kasten", "Schachtel", "Kiste"), englishWords = listOf("box")),
        VocabularyEntry(germanWords = listOf("öffnen", "aufmachen"), englishWords = listOf("(to) open")),
        VocabularyEntry(germanWords = listOf("Zug"), englishWords = listOf("train")),
        VocabularyEntry(germanWords = listOf("Fenster"), englishWords = listOf("window")),
        VocabularyEntry(germanWords = listOf("halten", "festhalten"), englishWords = listOf("(to) hold")),
        VocabularyEntry(germanWords = listOf("geöffnet", "offen", "aufgeschlagen"), englishWords = listOf("open")),
        VocabularyEntry(germanWords = listOf("Frau"), englishWords = listOf("woman", "women (pl.)")),
        VocabularyEntry(germanWords = listOf("Mann"), englishWords = listOf("man", "men (pl.)")),
        VocabularyEntry(germanWords = listOf("sich vordrängeln"), englishWords = listOf("(to) jump the queue")),
        VocabularyEntry(germanWords = listOf("britisch", "Brite", "Britin"), englishWords = listOf("British")),
        VocabularyEntry(germanWords = listOf("stehen"), englishWords = listOf("(to) stand")),
        VocabularyEntry(germanWords = listOf("gehen", "laufen"), englishWords = listOf("(to) walk")),
        VocabularyEntry(germanWords = listOf("Rolltreppe"), englishWords = listOf("escalator")),
        VocabularyEntry(germanWords = listOf("Schloss", "Burg"), englishWords = listOf("castle")),
        VocabularyEntry(germanWords = listOf("Flagge", "Fahne"), englishWords = listOf("flag")),
        VocabularyEntry(germanWords = listOf("Strand"), englishWords = listOf("beach")),
        VocabularyEntry(germanWords = listOf("Meer"), englishWords = listOf("sea")),
        VocabularyEntry(germanWords = listOf("kalt"), englishWords = listOf("cold")),
        VocabularyEntry(germanWords = listOf("Fels", "Stein"), englishWords = listOf("rock")),
        VocabularyEntry(germanWords = listOf("besonders", "speziell"), englishWords = listOf("special")),
        VocabularyEntry(germanWords = listOf("Form"), englishWords = listOf("shape")),
        VocabularyEntry(germanWords = listOf("viel", "viele", "eine Menge"), englishWords = listOf("a lot of")),
        VocabularyEntry(germanWords = listOf("hoch", "groß"), englishWords = listOf("high")),
        VocabularyEntry(germanWords = listOf("Berg"), englishWords = listOf("mountain")),
        VocabularyEntry(germanWords = listOf("Wald"), englishWords = listOf("forest")),
        VocabularyEntry(germanWords = listOf("Insel"), englishWords = listOf("island")),
        VocabularyEntry(germanWords = listOf("Stadtplan", "Landkarte"), englishWords = listOf("map")),
        VocabularyEntry(germanWords = listOf("nördlich", "im Norden"), englishWords = listOf("north")),
        VocabularyEntry(germanWords = listOf("Schaf"), englishWords = listOf("sheep", "sheep (pl.)")),
        VocabularyEntry(germanWords = listOf("separat", "getrennt", "verschieden"), englishWords = listOf("separate")),
        VocabularyEntry(germanWords = listOf("Museum"), englishWords = listOf("museum")),
        VocabularyEntry(germanWords = listOf("Hauptstadt"), englishWords = listOf("capital")),
        VocabularyEntry(germanWords = listOf("Großstadt", "Stadt"), englishWords = listOf("city")),
        VocabularyEntry(germanWords = listOf("Fakt", "Tatsache"), englishWords = listOf("fact")),
        VocabularyEntry(germanWords = listOf("berühmteste", "berühmtester", "berühmtestes"), englishWords = listOf("most famous")),
        VocabularyEntry(germanWords = listOf("berühmt"), englishWords = listOf("famous")),
        VocabularyEntry(germanWords = listOf("Sehenswürdigkeit", "Anblick"), englishWords = listOf("sight")),
        VocabularyEntry(germanWords = listOf("Königin"), englishWords = listOf("queen")),
        VocabularyEntry(germanWords = listOf("Fluss"), englishWords = listOf("river")),
        VocabularyEntry(germanWords = listOf("fahren", "reiten"), englishWords = listOf("(to) ride")),
        VocabularyEntry(germanWords = listOf("am interessantesten"), englishWords = listOf("most interesting")),
        VocabularyEntry(germanWords = listOf("Stadt"), englishWords = listOf("town")),
        VocabularyEntry(germanWords = listOf("nahe", "in der Nähe von"), englishWords = listOf("near")),
        VocabularyEntry(germanWords = listOf("Dorf"), englishWords = listOf("village")),
        VocabularyEntry(germanWords = listOf("Kirche"), englishWords = listOf("church")),
        VocabularyEntry(germanWords = listOf("Kino"), englishWords = listOf("cinema")),
        VocabularyEntry(germanWords = listOf("Theater"), englishWords = listOf("theatre")),
        VocabularyEntry(germanWords = listOf("Konzert"), englishWords = listOf("concert")),
    )

    val unit_4 = listOf(
        VocabularyEntry(germanWords = listOf("kosten"), englishWords = listOf("(to) cost")),
        VocabularyEntry(germanWords = listOf("Schiff"), englishWords = listOf("ship")),
        VocabularyEntry(germanWords = listOf("hinüber", "über"), englishWords = listOf("over")),
        VocabularyEntry(germanWords = listOf("Fuß"), englishWords = listOf("foot", "feet (pl.)")),
        VocabularyEntry(germanWords = listOf("Pier", "Hafendamm"), englishWords = listOf("pier")),
        VocabularyEntry(germanWords = listOf("frei", "kostenfrei"), englishWords = listOf("free")),
        VocabularyEntry(germanWords = listOf("Wasserrutsche"), englishWords = listOf("water slide")),
        VocabularyEntry(germanWords = listOf("Freizeitzentrum"), englishWords = listOf("leisure centre")),
        VocabularyEntry(germanWords = listOf("Freizeit"), englishWords = listOf("free time")),
        VocabularyEntry(germanWords = listOf("Blick"), englishWords = listOf("look")),
        VocabularyEntry(germanWords = listOf("auf der anderen Seite von", "über", "hinüber", "herüber", "quer durch"), englishWords = listOf("across"))
    )

    val combinedList = unit_1 + unit_2 + unit_3 + unit_4

    val allLists: Map<String, List<VocabularyEntry>> = mapOf(
        "Wiederholung (alle Vokabeln)" to combinedList,
        "Unit 1" to unit_1,
        "Unit 2" to unit_2,
        "Unit 3" to unit_3,
        "Unit 4" to unit_4

    )

    // Standardmäßig ausgewählte Liste oder null, wenn keine Vorauswahl getroffen werden soll
    var currentListName: String? = allLists.keys.firstOrNull() // Wählt die erste Liste als Standard

    fun getCurrentVocabularyList(): List<VocabularyEntry>? {
        return currentListName?.let { allLists[it] }
    }
}