package com.example.vokabeltrainer

// Datenklasse, die hier benötigt wird
data class VocabularyEntry(
    val germanWords: List<String>,
    val englishWords: List<String>
)

object Vocabulary_cl_5 {
    val cl_5_unit_1 = listOf(
        VocabularyEntry(germanWords = listOf("Hund", ), englishWords = listOf("dog")),
        VocabularyEntry(germanWords = listOf("Maus"), englishWords = listOf("mice")),
        VocabularyEntry(germanWords = listOf("Ball"), englishWords = listOf("ball")),
        VocabularyEntry(germanWords = listOf("verschieden", "unterschiedlich"), englishWords = listOf("different")),
        VocabularyEntry(germanWords = listOf("knapp", "geschlossen"), englishWords = listOf("close")),
        VocabularyEntry(germanWords = listOf("See"), englishWords = listOf("lake")),
        VocabularyEntry(germanWords = listOf("Boot"), englishWords = listOf("boat")),
        VocabularyEntry(germanWords = listOf("Rätsel"), englishWords = listOf("puzzle")),
        VocabularyEntry(germanWords = listOf("Angst haben", "sich fürchten"), englishWords = listOf("scared")),
        VocabularyEntry(germanWords = listOf("Freund"), englishWords = listOf("friend")),
        VocabularyEntry(germanWords = listOf("Wort"), englishWords = listOf("word")),
        VocabularyEntry(germanWords = listOf("essen"), englishWords = listOf("eat")),
        VocabularyEntry(germanWords = listOf("derselbe", "der gleiche"), englishWords = listOf("the same")),
        VocabularyEntry(germanWords = listOf("deutsch"), englishWords = listOf("German")),
        VocabularyEntry(germanWords = listOf("rot"), englishWords = listOf("red")),
        VocabularyEntry(germanWords = listOf("grün"), englishWords = listOf("green")),
        VocabularyEntry(germanWords = listOf("gelb"), englishWords = listOf("yellow")),
        VocabularyEntry(germanWords = listOf("blau"), englishWords = listOf("blue")),
        VocabularyEntry(germanWords = listOf("grau"), englishWords = listOf("grey")),
        VocabularyEntry(germanWords = listOf("schwarz"), englishWords = listOf("black")),
        VocabularyEntry(germanWords = listOf("weis"), englishWords = listOf("white")),
        VocabularyEntry(germanWords = listOf("orange"), englishWords = listOf("orange")),
        VocabularyEntry(germanWords = listOf("Lila"), englishWords = listOf("purple")),
        VocabularyEntry(germanWords = listOf("braun"), englishWords = listOf("brown")),
        VocabularyEntry(germanWords = listOf("pink"), englishWords = listOf("pink")),
        VocabularyEntry(germanWords = listOf("null", "0"), englishWords = listOf("zero")),
        VocabularyEntry(germanWords = listOf("eins", "1"), englishWords = listOf("one")),
        VocabularyEntry(germanWords = listOf("zwei", "2"), englishWords = listOf("two")),
        VocabularyEntry(germanWords = listOf("drei", "3"), englishWords = listOf("three")),
        VocabularyEntry(germanWords = listOf("vier", "4"), englishWords = listOf("four")),
        VocabularyEntry(germanWords = listOf("fünf", "5"), englishWords = listOf("five")),
        VocabularyEntry(germanWords = listOf("sechs", "6"), englishWords = listOf("six")),
        VocabularyEntry(germanWords = listOf("sieben", "7"), englishWords = listOf("seven")),
        VocabularyEntry(germanWords = listOf("acht", "8"), englishWords = listOf("eight")),
        VocabularyEntry(germanWords = listOf("neun", "9"), englishWords = listOf("nine")),
        VocabularyEntry(germanWords = listOf("zehn", "10"), englishWords = listOf("ten")),
        VocabularyEntry(germanWords = listOf("elf", "11"), englishWords = listOf("eleven")),
        VocabularyEntry(germanWords = listOf("zwölf", "12"), englishWords = listOf("twelve")),
        VocabularyEntry(germanWords = listOf("zu Hause"), englishWords = listOf("at home")),
        VocabularyEntry(germanWords = listOf("Familie"), englishWords = listOf("family")),
        VocabularyEntry(germanWords = listOf("wohnen", "leben"), englishWords = listOf("to live")),
        VocabularyEntry(germanWords = listOf("Wohnung"), englishWords = listOf("flat")),
        VocabularyEntry(germanWords = listOf("in der Straße", "auf der Straße"), englishWords = listOf("in the street")),
        VocabularyEntry(germanWords = listOf("Haus"), englishWords = listOf("house")),
        VocabularyEntry(germanWords = listOf("Tür"), englishWords = listOf("door")),
        VocabularyEntry(germanWords = listOf("Fernsehen", "Fernseher"), englishWords = listOf("TV", "television")),
        VocabularyEntry(germanWords = listOf("Stuhl", "Sessel"), englishWords = listOf("chair")),
        VocabularyEntry(germanWords = listOf("Tisch"), englishWords = listOf("table")),
        VocabularyEntry(germanWords = listOf("Dusche"), englishWords = listOf("shower")),
        VocabularyEntry(germanWords = listOf("Bad", "Badewanne"), englishWords = listOf("bath")),
        VocabularyEntry(germanWords = listOf("Toilette"), englishWords = listOf("toilet")),
        VocabularyEntry(germanWords = listOf("Bett"), englishWords = listOf("bed")),
        VocabularyEntry(germanWords = listOf("Uhr"), englishWords = listOf("clock")),
        VocabularyEntry(germanWords = listOf("Kleiderschrank"), englishWords = listOf("wardrobe")),
        VocabularyEntry(germanWords = listOf("Küchenschrank", "Schrank"), englishWords = listOf("cupboard")),
        VocabularyEntry(germanWords = listOf("Herd"), englishWords = listOf("cooker")),
        VocabularyEntry(germanWords = listOf("Wohnzimmer"), englishWords = listOf("living room")),
        VocabularyEntry(germanWords = listOf("Schlafzimmer"), englishWords = listOf("bedroom")),
        VocabularyEntry(germanWords = listOf("Küche"), englishWords = listOf("kitchen")),
        VocabularyEntry(germanWords = listOf("Bad", "Badezimmer"), englishWords = listOf("bathroom")),
        VocabularyEntry(germanWords = listOf("gut"), englishWords = listOf("good")),
        VocabularyEntry(germanWords = listOf("Keks"), englishWords = listOf("biscuit")),
        VocabularyEntry(germanWords = listOf("unter"), englishWords = listOf("under")),
        VocabularyEntry(germanWords = listOf("helfen"), englishWords = listOf("help")),
        VocabularyEntry(germanWords = listOf("sammeln"), englishWords = listOf("collect")),
        VocabularyEntry(germanWords = listOf("neu"), englishWords = listOf("new")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small")),
        VocabularyEntry(germanWords = listOf("Schwester"), englishWords = listOf("sister")),
        VocabularyEntry(germanWords = listOf("Bruder"), englishWords = listOf("brother")),
        VocabularyEntry(germanWords = listOf("Vater"), englishWords = listOf("father")),
        VocabularyEntry(germanWords = listOf("Mutter"), englishWords = listOf("mother")),
        VocabularyEntry(germanWords = listOf("Cousin", "Cousine"), englishWords = listOf("cousin")),
        VocabularyEntry(germanWords = listOf("ein", "eine"), englishWords = listOf("an", "a")),
        VocabularyEntry(germanWords = listOf("Einzelkind"), englishWords = listOf("only child")),
        VocabularyEntry(germanWords = listOf("Papa"), englishWords = listOf("dad")),
        VocabularyEntry(germanWords = listOf("sie ist"), englishWords = listOf("she's")),
        VocabularyEntry(germanWords = listOf("ist nicht"), englishWords = listOf("isn't", "is not")),
        VocabularyEntry(germanWords = listOf("immer", "ständig"), englishWords = listOf("always")),
        VocabularyEntry(germanWords = listOf("einfach", "leicht"), englishWords = listOf("easy")),
        VocabularyEntry(germanWords = listOf("er ist"), englishWords = listOf("he's")),
        VocabularyEntry(germanWords = listOf("Mama"), englishWords = listOf("mum")),
        VocabularyEntry(germanWords = listOf("Onkel"), englishWords = listOf("uncle")),
        VocabularyEntry(germanWords = listOf("Tante"), englishWords = listOf("aunt")),
        VocabularyEntry(germanWords = listOf("Opa"), englishWords = listOf("grandad")),
        VocabularyEntry(germanWords = listOf("Oma"), englishWords = listOf("grandma")),
        VocabularyEntry(germanWords = listOf("Stammbaum"), englishWords = listOf("family tree")),
        VocabularyEntry(germanWords = listOf("Erzähle mir von"), englishWords = listOf("Tell me about")),
        VocabularyEntry(germanWords = listOf("Meerschweinchen"), englishWords = listOf("guinea pig")),
        VocabularyEntry(germanWords = listOf("still", "ruhig", "leise"), englishWords = listOf("quiet")),
        VocabularyEntry(germanWords = listOf("Sprache"), englishWords = listOf("language")),
        VocabularyEntry(germanWords = listOf("erst", "bloß", "nur"), englishWords = listOf("only")),
        VocabularyEntry(germanWords = listOf("falsch"), englishWords = listOf("wrong")),
        VocabularyEntry(germanWords = listOf("Danke"), englishWords = listOf("Thanks")),
        VocabularyEntry(germanWords = listOf("sehr"), englishWords = listOf("very")),
        VocabularyEntry(germanWords = listOf("einige", "ein paar", "etwas"), englishWords = listOf("some")),
        VocabularyEntry(germanWords = listOf("von"), englishWords = listOf("of")),
        VocabularyEntry(germanWords = listOf("grüßen", "Grüße ausrichten"), englishWords = listOf("to say hello")),
        VocabularyEntry(germanWords = listOf("zu", "nach", "auf", "in"), englishWords = listOf("to")),
        VocabularyEntry(germanWords = listOf("nett"), englishWords = listOf("nice")),
        VocabularyEntry(germanWords = listOf("cool"), englishWords = listOf("cool")),
        VocabularyEntry(germanWords = listOf("großartig"), englishWords = listOf("great")),
        VocabularyEntry(germanWords = listOf("witzig"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in Ordnung"), englishWords = listOf("OK")),
        VocabularyEntry(germanWords = listOf("verrückt"), englishWords = listOf("crazy")),
        VocabularyEntry(germanWords = listOf("ruhig"), englishWords = listOf("quiet")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small")),
        VocabularyEntry(germanWords = listOf("groß"), englishWords = listOf("tall")),
        VocabularyEntry(germanWords = listOf("freundlich"), englishWords = listOf("friendly")),
        VocabularyEntry(germanWords = listOf("schlau"), englishWords = listOf("clever")),
        VocabularyEntry(germanWords = listOf("albern", "dumm"), englishWords = listOf("silly")),
        VocabularyEntry(germanWords = listOf("laut"), englishWords = listOf("noisy")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("short")),
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
        VocabularyEntry(germanWords = listOf("da ist/sind", "es gibt"), englishWords = listOf("there is/are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("nett"), englishWords = listOf("nice")),
        VocabularyEntry(germanWords = listOf("cool"), englishWords = listOf("cool")),
        VocabularyEntry(germanWords = listOf("großartig"), englishWords = listOf("great")),
        VocabularyEntry(germanWords = listOf("witzig"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in Ordnung"), englishWords = listOf("OK")),
        VocabularyEntry(germanWords = listOf("verrückt"), englishWords = listOf("crazy")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small", "little")),
        VocabularyEntry(germanWords = listOf("groß"), englishWords = listOf("tall")),
        VocabularyEntry(germanWords = listOf("freundlich"), englishWords = listOf("friendly")),
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
        VocabularyEntry(germanWords = listOf("das ist/sind", "es gibt"), englishWords = listOf("there is/are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("Herr (Anrede)"), englishWords = listOf("Mr")),
        VocabularyEntry(germanWords = listOf("Frau (Anrede)"), englishWords = listOf("Mrs")),
        VocabularyEntry(germanWords = listOf("jetzt", "nun"), englishWords = listOf("now")),
        VocabularyEntry(germanWords = listOf("Auto"), englishWords = listOf("car")),
        VocabularyEntry(germanWords = listOf("überall", "überallhin"), englishWords = listOf("everywhere")),
        VocabularyEntry(germanWords = listOf("wieder", "noch einmal", "noch mal"), englishWords = listOf("again")),
        VocabularyEntry(germanWords = listOf("Fußboden"), englishWords = listOf("floor")),
        VocabularyEntry(germanWords = listOf("neben"), englishWords = listOf("next to")),
        VocabularyEntry(germanWords = listOf("vor"), englishWords = listOf("in front of")),
        VocabularyEntry(germanWords = listOf("zuhören", "anhören"), englishWords = listOf("listen (to)")),
        VocabularyEntry(germanWords = listOf("Idee", "Einfall"), englishWords = listOf("idea")),
        VocabularyEntry(germanWords = listOf("Dachboden"), englishWords = listOf("loft")),
        VocabularyEntry(germanWords = listOf("eigene/r/s"), englishWords = listOf("own")),
        VocabularyEntry(germanWords = listOf("Kleiderschrank"), englishWords = listOf("wardrobe")),
        VocabularyEntry(germanWords = listOf("Bett"), englishWords = listOf("bed")),
        VocabularyEntry(germanWords = listOf("Tisch"), englishWords = listOf("table")),
        VocabularyEntry(germanWords = listOf("Stuhl"), englishWords = listOf("chair")),
        VocabularyEntry(germanWords = listOf("Lampe"), englishWords = listOf("lamp")),
        VocabularyEntry(germanWords = listOf("Spiegel"), englishWords = listOf("mirror")),
        VocabularyEntry(germanWords = listOf("Regal", "Regale"), englishWords = listOf("shelf", "shelves")),
        VocabularyEntry(germanWords = listOf("Teppich", "Vorleger"), englishWords = listOf("rug")),
        VocabularyEntry(germanWords = listOf("Gitarre"), englishWords = listOf("guitar")),
        VocabularyEntry(germanWords = listOf("Skateboard"), englishWords = listOf("skateboard")),
        VocabularyEntry(germanWords = listOf("Poster"), englishWords = listOf("poster")),
        VocabularyEntry(germanWords = listOf("Spielzeug"), englishWords = listOf("toy")),
        VocabularyEntry(germanWords = listOf("Stofftier", "Stofftierchen"), englishWords = listOf("cuddly toy")),
        VocabularyEntry(germanWords = listOf("Computer"), englishWords = listOf("computer")),
        VocabularyEntry(germanWords = listOf("belebt", "beschäftigt"), englishWords = listOf("busy")),
        VocabularyEntry(germanWords = listOf("für", "wen", "?"), englishWords = listOf("who... for?")),
        VocabularyEntry(germanWords = listOf("auf Entdeckungsreise gehen", "erkunden", "erforschen"), englishWords = listOf("to explore")),
        VocabularyEntry(germanWords = listOf("beste/r/s"), englishWords = listOf("best")),
        VocabularyEntry(germanWords = listOf("Tasche", "Tüte"), englishWords = listOf("bag")),
        VocabularyEntry(germanWords = listOf("vielleicht"), englishWords = listOf("maybe")),
        VocabularyEntry(germanWords = listOf("nach (zeitlich)"), englishWords = listOf("after")),
        VocabularyEntry(germanWords = listOf("Besuch"), englishWords = listOf("visit")),
        VocabularyEntry(germanWords = listOf("nach draußen", "draußen", "außerhalb (von)"), englishWords = listOf("outside")),
        VocabularyEntry(germanWords = listOf("schrecklich", "furchtbar"), englishWords = listOf("awful")),
        VocabularyEntry(germanWords = listOf("Keine Sorge"), englishWords = listOf("Don't worry")),
        VocabularyEntry(germanWords = listOf("Satz"), englishWords = listOf("sentence")),
        VocabularyEntry(germanWords = listOf("richtig", "korrekt"), englishWords = listOf("right")),
        VocabularyEntry(germanWords = listOf("Ende", "Schluss (Geschichte)"), englishWords = listOf("ending")),
        VocabularyEntry(germanWords = listOf("über etw. sprechen", "über etw. erzählen"), englishWords = listOf("to talk about")),
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
        VocabularyEntry(germanWords = listOf("das ist", "sind", "es gibt"), englishWords = listOf("there is", "there are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("Herr", "Anrede"), englishWords = listOf("Mr")),
        VocabularyEntry(germanWords = listOf("Frau", "Anrede"), englishWords = listOf("Mrs")),
        VocabularyEntry(germanWords = listOf("jetzt", "nun"), englishWords = listOf("now")),
        VocabularyEntry(germanWords = listOf("Auto"), englishWords = listOf("car")),
        VocabularyEntry(germanWords = listOf("überall", "überallhin"), englishWords = listOf("everywhere")),
        VocabularyEntry(germanWords = listOf("wieder", "noch einmal", "noch mal"), englishWords = listOf("again")),
        VocabularyEntry(germanWords = listOf("Fußboden"), englishWords = listOf("floor")),
        VocabularyEntry(germanWords = listOf("neben"), englishWords = listOf("next to")),
        VocabularyEntry(germanWords = listOf("vor"), englishWords = listOf("in front of")),
        VocabularyEntry(germanWords = listOf("zuhören", "anhören"), englishWords = listOf("listen", "listen to")),
        VocabularyEntry(germanWords = listOf("Idee", "Einfall"), englishWords = listOf("idea")),
        VocabularyEntry(germanWords = listOf("Dachboden"), englishWords = listOf("loft")),
        VocabularyEntry(germanWords = listOf("eigen"), englishWords = listOf("own")),
        VocabularyEntry(germanWords = listOf("Tag"), englishWords = listOf("day")),
        VocabularyEntry(germanWords = listOf("glücklich", "froh"), englishWords = listOf("happy")),
        VocabularyEntry(germanWords = listOf("kann nicht"), englishWords = listOf("can't")),
        VocabularyEntry(germanWords = listOf("treffen", "sich treffen"), englishWords = listOf("to meet")),
        VocabularyEntry(germanWords = listOf("zeigen"), englishWords = listOf("to show")),
        VocabularyEntry(germanWords = listOf("Spiel"), englishWords = listOf("game")),
        VocabularyEntry(germanWords = listOf("wollen", "mögen"), englishWords = listOf("to want", "to")),
        VocabularyEntry(germanWords = listOf("spielen"), englishWords = listOf("to play")),
        VocabularyEntry(germanWords = listOf("langweilig"), englishWords = listOf("boring")),
        VocabularyEntry(germanWords = listOf("Du magst doch Sport", "Du stehst doch auf Sport"), englishWords = listOf("You're into sports")),
        VocabularyEntry(germanWords = listOf("Versuch es mal mit Inlineskating", "Probier es mal mit Inlineskating"), englishWords = listOf("Try skating")),
        VocabularyEntry(germanWords = listOf("schnell"), englishWords = listOf("fast")),
        VocabularyEntry(germanWords = listOf("Tut mir Leid"), englishWords = listOf("I'm sorry")),
        VocabularyEntry(germanWords = listOf("Mir geht's gut"), englishWords = listOf("I'm fine")),
        VocabularyEntry(germanWords = listOf("niedlich", "süß"), englishWords = listOf("cute")),
        VocabularyEntry(germanWords = listOf("Glücksbringer", "Talisman"), englishWords = listOf("Lucky charm")),
        VocabularyEntry(germanWords = listOf("so", "also"), englishWords = listOf("so")),
        VocabularyEntry(germanWords = listOf("Badminton spielen"), englishWords = listOf("play badminton")),
        VocabularyEntry(germanWords = listOf("Basketball spielen"), englishWords = listOf("play basketball")),
        VocabularyEntry(germanWords = listOf("Fußball spielen"), englishWords = listOf("play football")),
        VocabularyEntry(germanWords = listOf("Volleyball spielen"), englishWords = listOf("play volleyball")),
        VocabularyEntry(germanWords = listOf("Tennis spielen"), englishWords = listOf("play tennis")),
        VocabularyEntry(germanWords = listOf("Handball spielen"), englishWords = listOf("play handball")),
        VocabularyEntry(germanWords = listOf("Computer Spiele spielen"), englishWords = listOf("play (Computer) games")),
        VocabularyEntry(germanWords = listOf("mit Tieren"), englishWords = listOf("with animals")),
        VocabularyEntry(germanWords = listOf("zu Hause"), englishWords = listOf("at home")),
        VocabularyEntry(germanWords = listOf("außerhalb"), englishWords = listOf("outside")),
        VocabularyEntry(germanWords = listOf("bootfahren"), englishWords = listOf("go boating")),
        VocabularyEntry(germanWords = listOf("Fahrradfahren"), englishWords = listOf("go cycling")),
        VocabularyEntry(germanWords = listOf("inlineskates fahren"), englishWords = listOf("go inline skating")),
        VocabularyEntry(germanWords = listOf("schwimmen gehen"), englishWords = listOf("go swimming")),
        VocabularyEntry(germanWords = listOf("Pferde reiten"), englishWords = listOf("horse-riding")),
        VocabularyEntry(germanWords = listOf("Skifahren"), englishWords = listOf("skiing")),
        VocabularyEntry(germanWords = listOf("snowboardfahren"), englishWords = listOf("snowboarding")),
        VocabularyEntry(germanWords = listOf("Musik machen"), englishWords = listOf("make music")),
        VocabularyEntry(germanWords = listOf("Modelle machen"), englishWords = listOf("make models")),
        VocabularyEntry(germanWords = listOf("SMS", "Kurznachricht"), englishWords = listOf("text (message)")),
        VocabularyEntry(germanWords = listOf("Lesen"), englishWords = listOf("reading")),
        VocabularyEntry(germanWords = listOf("Musik"), englishWords = listOf("music")),
        VocabularyEntry(germanWords = listOf("anmalen", "malen"), englishWords = listOf("to paint")),
        VocabularyEntry(germanWords = listOf("Schwimmen gehen"), englishWords = listOf("to go swimming")),
        VocabularyEntry(germanWords = listOf("Lesen"), englishWords = listOf("to read")),
        VocabularyEntry(germanWords = listOf("Buch"), englishWords = listOf("book")),
        VocabularyEntry(germanWords = listOf("fotografieren", "Fotos machen"), englishWords = listOf("to take photos")),
        VocabularyEntry(germanWords = listOf("beobachten", "sich ansehen", "zuschauen"), englishWords = listOf("to watch")),
        VocabularyEntry(germanWords = listOf("Karten", "Spielkarten"), englishWords = listOf("card")),
        VocabularyEntry(germanWords = listOf("Zeitschrift"), englishWords = listOf("magazine")),
        VocabularyEntry(germanWords = listOf("fernsehen"), englishWords = listOf("to watch TV")),
        VocabularyEntry(germanWords = listOf("DVD"), englishWords = listOf("DVD")),
        VocabularyEntry(germanWords = listOf("Ich auch"), englishWords = listOf("Me too")),
        VocabularyEntry(germanWords = listOf("Fahrrad"), englishWords = listOf("bike")),
        // @formatter:on
    )

    val cl_5_unit_2 = listOf(
        VocabularyEntry(germanWords = listOf("Regel"), englishWords = listOf("rule")),
        VocabularyEntry(germanWords = listOf("Handbuch", "Kalender"), englishWords = listOf("planner")),
        VocabularyEntry(germanWords = listOf("Mittagessen"), englishWords = listOf("lunch")),
        VocabularyEntry(germanWords = listOf("Cafeteria"), englishWords = listOf("cafeteria")),
        VocabularyEntry(germanWords = listOf("Geld"), englishWords = listOf("money")),
        VocabularyEntry(germanWords = listOf("Automat", "Maschine", "Apparat", "Gerät"), englishWords = listOf("machine")),
        VocabularyEntry(germanWords = listOf("bezahlen"), englishWords = listOf("to pay (for)")),
        VocabularyEntry(germanWords = listOf("Finger"), englishWords = listOf("finger")),
        VocabularyEntry(germanWords = listOf("Kunstunterricht"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("kaufen"), englishWords = listOf("to buy")),
        VocabularyEntry(germanWords = listOf("Süßigkeiten", "Bonbons"), englishWords = listOf("sweets")),
        VocabularyEntry(germanWords = listOf("Geschäft", "Laden"), englishWords = listOf("shop")),
        VocabularyEntry(germanWords = listOf("Füller"), englishWords = listOf("pen")),
        VocabularyEntry(germanWords = listOf("Bleistift", "Buntstift"), englishWords = listOf("pencil")),
        VocabularyEntry(germanWords = listOf("Federmappchen", "Mäppchen"), englishWords = listOf("pencil-case")),
        VocabularyEntry(germanWords = listOf("Übungsheft"), englishWords = listOf("exercise book")),
        VocabularyEntry(germanWords = listOf("Lineal"), englishWords = listOf("ruler")),
        VocabularyEntry(germanWords = listOf("Radiergummi"), englishWords = listOf("rubber")),
        VocabularyEntry(germanWords = listOf("Uniform"), englishWords = listOf("uniform")),
        VocabularyEntry(germanWords = listOf("Aufnahmestudie", "Tonstudio"), englishWords = listOf("recording studio")),
        VocabularyEntry(germanWords = listOf("Klassenlehrer-in"), englishWords = listOf("tutor")),
        VocabularyEntry(germanWords = listOf("Klassenzimmer"), englishWords = listOf("classroom")),
        VocabularyEntry(germanWords = listOf("Klassenkamerad-in", "Mitschüler-in"), englishWords = listOf("classmates")),
        VocabularyEntry(germanWords = listOf("besitzen", "haben"), englishWords = listOf("to have", "to have got")),
        VocabularyEntry(germanWords = listOf("Frage"), englishWords = listOf("question")),
        VocabularyEntry(germanWords = listOf("heute"), englishWords = listOf("today")),
        VocabularyEntry(germanWords = listOf("Schultasche"), englishWords = listOf("schoolbag")),
        VocabularyEntry(germanWords = listOf("Klasse", "Tutoriumsgruppe"), englishWords = listOf("tutor group")),
        VocabularyEntry(germanWords = listOf("Guten Morgen"), englishWords = listOf("Good morning")),
        VocabularyEntry(germanWords = listOf("jeder", "alle"), englishWords = listOf("everyone")),
        VocabularyEntry(germanWords = listOf("Schüler", "Schülerin", "Student", "Studentin"), englishWords = listOf("student")),
        VocabularyEntry(germanWords = listOf("nennen"), englishWords = listOf("to call")),
        VocabularyEntry(germanWords = listOf("ihn", "ihm"), englishWords = listOf("him")),
        VocabularyEntry(germanWords = listOf("kein", "keine"), englishWords = listOf("no")),
        VocabularyEntry(germanWords = listOf("Ich singe und tanze gerne"), englishWords = listOf("I like singing and dancing")),
        VocabularyEntry(germanWords = listOf("singen"), englishWords = listOf("to sing")),
        VocabularyEntry(germanWords = listOf("tanzen"), englishWords = listOf("to dance")),
        VocabularyEntry(germanWords = listOf("Projekt"), englishWords = listOf("project")),
        VocabularyEntry(germanWords = listOf("tja", "nun"), englishWords = listOf("well")),
        VocabularyEntry(germanWords = listOf("etwas"), englishWords = listOf("something")),
        VocabularyEntry(germanWords = listOf("Warte ab"), englishWords = listOf("Wait and see")),
        VocabularyEntry(germanWords = listOf("Lehrer", "Lehrerin"), englishWords = listOf("teacher")),
        VocabularyEntry(germanWords = listOf("Tafel"), englishWords = listOf("board")),
        VocabularyEntry(germanWords = listOf("Gruppe", "Klasse"), englishWords = listOf("group")),
        VocabularyEntry(germanWords = listOf("viele", "jede Menge"), englishWords = listOf("lots of")),
        VocabularyEntry(germanWords = listOf("Büro"), englishWords = listOf("office")),
        VocabularyEntry(germanWords = listOf("Großeltern"), englishWords = listOf("grandparents")),
        VocabularyEntry(germanWords = listOf("Talentwettbewerb"), englishWords = listOf("talent show")),
        VocabularyEntry(germanWords = listOf("schicken", "senden"), englishWords = listOf("to send")),
        VocabularyEntry(germanWords = listOf("Essen", "Lebensmittel"), englishWords = listOf("food")),
        VocabularyEntry(germanWords = listOf("Karotte", "Möhre"), englishWords = listOf("carrot")),
        VocabularyEntry(germanWords = listOf("Pudding", "Nachtisch"), englishWords = listOf("pudding")),
        VocabularyEntry(germanWords = listOf("Restaurant", "Gaststätte"), englishWords = listOf("restaurant")),
        VocabularyEntry(germanWords = listOf("Taschengeld"), englishWords = listOf("pocket money")),
        VocabularyEntry(germanWords = listOf("benutzen", "verwenden", "gebrauchen"), englishWords = listOf("to use")),
        VocabularyEntry(germanWords = listOf("Bitte schön", "Hier sind Sie", "Hier bist du"), englishWords = listOf("here you are")),
        VocabularyEntry(germanWords = listOf("sei höflich", "seid höflich"), englishWords = listOf("be polite")),
        VocabularyEntry(germanWords = listOf("wessen"), englishWords = listOf("whose")),
        VocabularyEntry(germanWords = listOf("Deutsche Schüler haben Glück"), englishWords = listOf("German students are lucky")),
        VocabularyEntry(germanWords = listOf("Unterrichtsstunde", "Schulstunde", "Unterricht"), englishWords = listOf("lesson")),
        VocabularyEntry(germanWords = listOf("Gebäude"), englishWords = listOf("building")),
        VocabularyEntry(germanWords = listOf("Kunst"), englishWords = listOf("Art")),
        VocabularyEntry(germanWords = listOf("Englisch"), englishWords = listOf("English")),
        VocabularyEntry(germanWords = listOf("Deutsch"), englishWords = listOf("German")),
        VocabularyEntry(germanWords = listOf("Erdkunde", "Geografie"), englishWords = listOf("Geography")),
        VocabularyEntry(germanWords = listOf("Mathematik", "Mathe"), englishWords = listOf("Maths")),
        VocabularyEntry(germanWords = listOf("Naturwissenschaften"), englishWords = listOf("Science")),
        VocabularyEntry(germanWords = listOf("Musik"), englishWords = listOf("Music")),
        VocabularyEntry(germanWords = listOf("Latein"), englishWords = listOf("Latin")),
        VocabularyEntry(germanWords = listOf("Französisch"), englishWords = listOf("French")),
        VocabularyEntry(germanWords = listOf("Geschichte"), englishWords = listOf("History")),
        VocabularyEntry(germanWords = listOf("Sport"), englishWords = listOf("PE", "Physical Education")),
        VocabularyEntry(germanWords = listOf("Religion"), englishWords = listOf("RE", "Religious Education")),
        VocabularyEntry(germanWords = listOf("starren", "anstarren"), englishWords = listOf("to stare")),
        VocabularyEntry(germanWords = listOf("lustig", "witzig"), englishWords = listOf("funny")),
        VocabularyEntry(germanWords = listOf("Mittagspause"), englishWords = listOf("the lunch break")),
        VocabularyEntry(germanWords = listOf("sie", "ihnen"), englishWords = listOf("them")),
        VocabularyEntry(germanWords = listOf("vergessen"), englishWords = listOf("to forget")),
        VocabularyEntry(germanWords = listOf("machen", "tun"), englishWords = listOf("to do")),
        VocabularyEntry(germanWords = listOf("lustig", "fröhlich"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in", "in...hinein"), englishWords = listOf("into")),
        VocabularyEntry(germanWords = listOf("allein", "ohne fremde Hilfe"), englishWords = listOf("alone")),
        VocabularyEntry(germanWords = listOf("bringen", "mitbringen"), englishWords = listOf("to bring")),
        VocabularyEntry(germanWords = listOf("zu spät sein", "zu spät kommen"), englishWords = listOf("to be late")),
        VocabularyEntry(germanWords = listOf("sein"), englishWords = listOf("to be")),
        VocabularyEntry(germanWords = listOf("anhaben", "tragen"), englishWords = listOf("to wear")),
        VocabularyEntry(germanWords = listOf("rennen", "laufen"), englishWords = listOf("to run")),
        VocabularyEntry(germanWords = listOf("Hausaufgaben"), englishWords = listOf("homework")),
        VocabularyEntry(germanWords = listOf("unhöflich", "unverschämt"), englishWords = listOf("rude")),
        VocabularyEntry(germanWords = listOf("sitzen"), englishWords = listOf("to sit")),
        VocabularyEntry(germanWords = listOf("anschauen", "ansehen"), englishWords = listOf("to look at")),
        VocabularyEntry(germanWords = listOf("wenn", "wann", "als"), englishWords = listOf("when")),
        VocabularyEntry(germanWords = listOf("schon", "bereits"), englishWords = listOf("already")),
        VocabularyEntry(germanWords = listOf("hinzufügen", "ergänzen"), englishWords = listOf("to add")),
        VocabularyEntry(germanWords = listOf("Pommes frites"), englishWords = listOf("chips")),
        VocabularyEntry(germanWords = listOf("Ende", "Schluss"), englishWords = listOf("end")),
        VocabularyEntry(germanWords = listOf("da drüben", "dort drüben"), englishWords = listOf("over there")),
        VocabularyEntry(germanWords = listOf("diese (hier)"), englishWords = listOf("these")),
        VocabularyEntry(germanWords = listOf("jene", "die dort"), englishWords = listOf("those")),
        VocabularyEntry(germanWords = listOf("finden", "herausfinden"), englishWords = listOf("to find")),
        VocabularyEntry(germanWords = listOf("jemandem einen Streich spielen"), englishWords = listOf("to play a trick on")),
        VocabularyEntry(germanWords = listOf("Woche"), englishWords = listOf("week")),
        VocabularyEntry(germanWords = listOf("vor", "bevor"), englishWords = listOf("before")),
        VocabularyEntry(germanWords = listOf("arbeiten"), englishWords = listOf("to work")),
        VocabularyEntry(germanWords = listOf("Paar"), englishWords = listOf("pair")),
        VocabularyEntry(germanWords = listOf("Präsentation", "Vortrag"), englishWords = listOf("presentation")),
        VocabularyEntry(germanWords = listOf("Aufnahme", "Aufzeichnung"), englishWords = listOf("recording")),
        VocabularyEntry(germanWords = listOf("Gedicht"), englishWords = listOf("poem")),
        VocabularyEntry(germanWords = listOf("sicher"), englishWords = listOf("sure")),
        VocabularyEntry(germanWords = listOf("Stimme"), englishWords = listOf("voice")),
        VocabularyEntry(germanWords = listOf("nächste", "nächster", "nächstes", "der Nächste", "die Nächste"), englishWords = listOf("next")),
        VocabularyEntry(germanWords = listOf("eifersüchtig sein (auf)", "neidisch sein (auf)"), englishWords = listOf("to be jealous (of)")),
        VocabularyEntry(germanWords = listOf("beliebt", "populär"), englishWords = listOf("popular")),
        VocabularyEntry(germanWords = listOf("König"), englishWords = listOf("king")),
        VocabularyEntry(germanWords = listOf("Klasse"), englishWords = listOf("class")),
        VocabularyEntry(germanWords = listOf("Komm schon!", "Komm jetzt!"), englishWords = listOf("Come on!")),
        VocabularyEntry(germanWords = listOf("Ein paar Minuten später"), englishWords = listOf("A few minutes later")),
        VocabularyEntry(germanWords = listOf("Ich höre...", "Ich habe gehört, dass..."), englishWords = listOf("I hear...")),
        VocabularyEntry(germanWords = listOf("gerade", "nur", "einfach"), englishWords = listOf("just")),
        VocabularyEntry(germanWords = listOf("Witz"), englishWords = listOf("joke")),
        VocabularyEntry(germanWords = listOf("wirklich"), englishWords = listOf("really")),
        VocabularyEntry(germanWords = listOf("viel"), englishWords = listOf("much")),
        VocabularyEntry(germanWords = listOf("Zeit"), englishWords = listOf("time")),
        VocabularyEntry(germanWords = listOf("kennen", "wissen"), englishWords = listOf("to know")),
        VocabularyEntry(germanWords = listOf("Du bist dran"), englishWords = listOf("It's your turn")),
        VocabularyEntry(germanWords = listOf("Mach das aus!", "Macht das aus!", "Hör auf!", "Hört auf!"), englishWords = listOf("Stop it!")),
        VocabularyEntry(germanWords = listOf("lachen"), englishWords = listOf("to laugh")),
        VocabularyEntry(germanWords = listOf("wütend", "zornig", "verärgert", "böse"), englishWords = listOf("angry")),
        VocabularyEntry(germanWords = listOf("geben", "schenken"), englishWords = listOf("to give")),
        VocabularyEntry(germanWords = listOf("denken", "nachdenken"), englishWords = listOf("to think")),
        VocabularyEntry(germanWords = listOf("Ärger machen", "in Schwierigkeiten bringen"), englishWords = listOf("to make trouble")),
        VocabularyEntry(germanWords = listOf("Er hat recht."), englishWords = listOf("He's right.")),
        VocabularyEntry(germanWords = listOf("Story", "Geschichte", "Erzählung"), englishWords = listOf("story", "stories")),
        VocabularyEntry(germanWords = listOf("weil", "da"), englishWords = listOf("because"))
    )

    val cl_5_unit_3 = listOf(
        VocabularyEntry(germanWords = listOf("Käse"), englishWords = listOf("cheese")),
        VocabularyEntry(germanWords = listOf("vormittags (Uhrzeit)"), englishWords = listOf("a.m.")),
        VocabularyEntry(germanWords = listOf("nachmittags (Uhrzeit)", "abends (Uhrzeit)"), englishWords = listOf("p.m.")),
        VocabularyEntry(germanWords = listOf("Überraschung"), englishWords = listOf("surprise")),
        VocabularyEntry(germanWords = listOf("Koch-AG"), englishWords = listOf("Cooking Club")),
        VocabularyEntry(germanWords = listOf("Verein", "Klub", "AG"), englishWords = listOf("club")),
        VocabularyEntry(germanWords = listOf("mit dem Fahrrad"), englishWords = listOf("by bike")),
        VocabularyEntry(germanWords = listOf("sich hinsetzen", "sich setzen"), englishWords = listOf("to sit down")),
        VocabularyEntry(germanWords = listOf("frühstücken"), englishWords = listOf("to have breakfast")),
        VocabularyEntry(germanWords = listOf("Es ist Zeit aufzustehen!"), englishWords = listOf("Time to get up!")),
        VocabularyEntry(germanWords = listOf("aufräumen", "in Ordnung bringen"), englishWords = listOf("to tidy")),
        VocabularyEntry(germanWords = listOf("so machst du..."), englishWords = listOf("this is how you (do)")),
        VocabularyEntry(germanWords = listOf("schlafen"), englishWords = listOf("to sleep")),
        VocabularyEntry(germanWords = listOf("ins Bett gehen"), englishWords = listOf("to go to bed")),
        VocabularyEntry(germanWords = listOf("aufräumen", "in Ordnung bringen"), englishWords = listOf("to tidy")),
        VocabularyEntry(germanWords = listOf("so machst du..."), englishWords = listOf("this is how you (do)")),
        VocabularyEntry(germanWords = listOf("schlafen"), englishWords = listOf("to sleep")),
        VocabularyEntry(germanWords = listOf("ins Bett gehen"), englishWords = listOf("to go to bed")),
        VocabularyEntry(germanWords = listOf("Wie spät ist es?", "Wie viel Uhr ist es?"), englishWords = listOf("What's the time?")),
        VocabularyEntry(germanWords = listOf("jede", "jeder", "jedes"), englishWords = listOf("every")),
        VocabularyEntry(germanWords = listOf("kommen"), englishWords = listOf("to come")),
        VocabularyEntry(germanWords = listOf("nach Hause"), englishWords = listOf("home")),
        VocabularyEntry(germanWords = listOf("Abendessen"), englishWords = listOf("dinner")),
        VocabularyEntry(germanWords = listOf("um halb acht"), englishWords = listOf("at 7:30")),
        VocabularyEntry(germanWords = listOf("dann", "danach"), englishWords = listOf("then")),
        VocabularyEntry(germanWords = listOf("nie", "niemals"), englishWords = listOf("never")),
        VocabularyEntry(germanWords = listOf("Morgen", "Vormittag"), englishWords = listOf("morning")),
        VocabularyEntry(germanWords = listOf("Stiefmutter"), englishWords = listOf("stepmum")),
        VocabularyEntry(germanWords = listOf("wenn", "falls", "ob"), englishWords = listOf("if")),
        VocabularyEntry(germanWords = listOf("bis"), englishWords = listOf("till")),
        VocabularyEntry(germanWords = listOf("danach"), englishWords = listOf("after that")),
        VocabularyEntry(germanWords = listOf("montags"), englishWords = listOf("on Mondays")),
        VocabularyEntry(germanWords = listOf("Korbball"), englishWords = listOf("netball")),
        VocabularyEntry(germanWords = listOf("anders", "andere/-r/-s", "weitere"), englishWords = listOf("other")),
        VocabularyEntry(germanWords = listOf("sofort gleich"), englishWords = listOf("right away")),
        VocabularyEntry(germanWords = listOf("oft", "häufig"), englishWords = listOf("often")),
        VocabularyEntry(germanWords = listOf("Abend"), englishWords = listOf("evening")),
        VocabularyEntry(germanWords = listOf("manchmal"), englishWords = listOf("sometimes")),
        VocabularyEntry(germanWords = listOf("normalerweise", "gewöhnlich", "meistens"), englishWords = listOf("usually")),
        VocabularyEntry(germanWords = listOf("lang"), englishWords = listOf("long")),
        VocabularyEntry(germanWords = listOf("Ich bin hundemüde"), englishWords = listOf("I'm dog-tired")),
        VocabularyEntry(germanWords = listOf("müde"), englishWords = listOf("tired")),
        VocabularyEntry(germanWords = listOf("Wie wäre es mit...?", "Was ist mit...?"), englishWords = listOf("What about...?")),
        VocabularyEntry(germanWords = listOf("Nachmittag"), englishWords = listOf("afternoon")),
        VocabularyEntry(germanWords = listOf("suchen nach"), englishWords = listOf("to look for")),
        VocabularyEntry(germanWords = listOf("schnarchen"), englishWords = listOf("snore")),
        VocabularyEntry(germanWords = listOf("Zimmergenosse", "Zimmergenossin"), englishWords = listOf("roommate")),
        VocabularyEntry(germanWords = listOf("Trainer", "Trainerin"), englishWords = listOf("coach")),
        VocabularyEntry(germanWords = listOf("Letzte", "Letzter", "Letztes"), englishWords = listOf("last")),
        VocabularyEntry(germanWords = listOf("morgen"), englishWords = listOf("tomorrow")),
        VocabularyEntry(germanWords = listOf("Sie geht mir auf die Nerven"), englishWords = listOf("She gets on my nerves")),
        VocabularyEntry(germanWords = listOf("Oma"), englishWords = listOf("granny")),
        VocabularyEntry(germanWords = listOf("aufpassen auf", "hüten", "sich kümmern um"), englishWords = listOf("to look after")),
        VocabularyEntry(germanWords = listOf("fragen", "bitten"), englishWords = listOf("to ask")),
        VocabularyEntry(germanWords = listOf("sprechen", "reden"), englishWords = listOf("to talk")),
        VocabularyEntry(germanWords = listOf("aufhören (mit)", "anhalten", "stoppen"), englishWords = listOf("to stop")),
        VocabularyEntry(germanWords = listOf("plaudern", "chatten (sich online unterhalten)"), englishWords = listOf("to chat")),
        VocabularyEntry(germanWords = listOf("sogar", "selbst"), englishWords = listOf("even")),
        VocabularyEntry(germanWords = listOf("Arbeit"), englishWords = listOf("work")),
        VocabularyEntry(germanWords = listOf("Tierarzt", "Tierärztin"), englishWords = listOf("vet")),
        VocabularyEntry(germanWords = listOf("Nachbar", "Nachbarin"), englishWords = listOf("neighbour")),
        VocabularyEntry(germanWords = listOf("nehmen", "mitnehmen", "wegnehmen", "bringen", "mitbringen"), englishWords = listOf("(to) take")),
        VocabularyEntry(germanWords = listOf("Haustier"), englishWords = listOf("pet")),
        VocabularyEntry(germanWords = listOf("Arztpraxis", "Praxis", "Praxisräume"), englishWords = listOf("surgery")),
        VocabularyEntry(germanWords = listOf("warum"), englishWords = listOf("why")),
        VocabularyEntry(germanWords = listOf("Vorsicht!", "Pass auf!", "Passt auf!"), englishWords = listOf("Be careful")),
        VocabularyEntry(germanWords = listOf("Fehler"), englishWords = listOf("mistake")),
        VocabularyEntry(germanWords = listOf("Kochen"), englishWords = listOf("cooking")),
        VocabularyEntry(germanWords = listOf("Dialog", "Gespräch"), englishWords = listOf("dialogue")),
        VocabularyEntry(germanWords = listOf("Redner", "Rednerin", "Sprecher", "Sprecherin"), englishWords = listOf("speaker")),
        VocabularyEntry(germanWords = listOf("Worum geht es in...?", "Worum geht es im...?"), englishWords = listOf("What is... about?")),
        VocabularyEntry(germanWords = listOf("gehen um", "handeln von"), englishWords = listOf("to be about")),
        VocabularyEntry(germanWords = listOf("herausfinden"), englishWords = listOf("to find out")),
        VocabularyEntry(germanWords = listOf("Situation"), englishWords = listOf("situation")),
        VocabularyEntry(germanWords = listOf("sich verbessern", "verbessern"), englishWords = listOf("(to) improve")),
        VocabularyEntry(germanWords = listOf("aufwärmen", "sich aufwärmen"), englishWords = listOf("(to) warm up")),
        VocabularyEntry(germanWords = listOf("Mund"), englishWords = listOf("mouth")),
        VocabularyEntry(germanWords = listOf("Ton", "Geräusch", "Klang"), englishWords = listOf("sound")),
        VocabularyEntry(germanWords = listOf("in Form kommen", "fit werden"), englishWords = listOf("(to) get fit")),
        VocabularyEntry(germanWords = listOf("Rhythmus"), englishWords = listOf("rhythm")),
        VocabularyEntry(germanWords = listOf("aufstehen (von einer Sitzgelegenheit)"), englishWords = listOf("(to) stand up")),
        VocabularyEntry(germanWords = listOf("Klatsche in die Hände", "Klatscht in die Hände"), englishWords = listOf("Clap your hands.")),
        VocabularyEntry(germanWords = listOf("laut"), englishWords = listOf("loud")),
        VocabularyEntry(germanWords = listOf("sehr"), englishWords = listOf("very much")),
        VocabularyEntry(germanWords = listOf("sprechen"), englishWords = listOf("(to) speak")),
        VocabularyEntry(germanWords = listOf("klar", "deutlich"), englishWords = listOf("clear")),
        VocabularyEntry(germanWords = listOf("eine Theaterszene spielen"), englishWords = listOf("acting a scene")),
        VocabularyEntry(germanWords = listOf("waschen", "sich waschen"), englishWords = listOf("(to) wash")),
        VocabularyEntry(germanWords = listOf("Gesicht"), englishWords = listOf("face")),
        VocabularyEntry(germanWords = listOf("machen", "tun", "bilden"), englishWords = listOf("(to) make")),
        VocabularyEntry(germanWords = listOf("früh"), englishWords = listOf("early")),
        VocabularyEntry(germanWords = listOf("auf Wiedersehen"), englishWords = listOf("goodbye")),
        VocabularyEntry(germanWords = listOf("bellen"), englishWords = listOf("(to) bark")),
        VocabularyEntry(germanWords = listOf("Angst haben (vor)"), englishWords = listOf("(to) be scared (of)")),
        VocabularyEntry(germanWords = listOf("wegrennen"), englishWords = listOf("(to) run away")),
        VocabularyEntry(germanWords = listOf("Spaß haben", "sich amüsieren"), englishWords = listOf("(to) have fun")),
        VocabularyEntry(germanWords = listOf("horchen auf"), englishWords = listOf("(to) listen for")),
        VocabularyEntry(germanWords = listOf("Sitz! (Befehl für Hunde)"), englishWords = listOf("Sit!")),
        VocabularyEntry(germanWords = listOf("um... herum", "umher"), englishWords = listOf("around")),
        VocabularyEntry(germanWords = listOf("Schwanz", "Schweif"), englishWords = listOf("tail")),
        VocabularyEntry(germanWords = listOf("viel zu lernen"), englishWords = listOf("a lot to learn")),
        VocabularyEntry(germanWords = listOf("setzen", "stellen", "legen"), englishWords = listOf("(to) put")),
        VocabularyEntry(germanWords = listOf("Getränk"), englishWords = listOf("drink")),
        VocabularyEntry(germanWords = listOf("hinfallen", "umkippen"), englishWords = listOf("(to) fall over")),
        VocabularyEntry(germanWords = listOf("werfen (nach)"), englishWords = listOf("(to) throw (at)")),
        VocabularyEntry(germanWords = listOf("Schuh"), englishWords = listOf("shoe")),
        VocabularyEntry(germanWords = listOf("einschlafen"), englishWords = listOf("(to) fall asleep")),
        VocabularyEntry(germanWords = listOf("jagen", "nachjagen"), englishWords = listOf("(to) chase")),
        VocabularyEntry(germanWords = listOf("Gesicht"), englishWords = listOf("face")),
        VocabularyEntry(germanWords = listOf("Mund"), englishWords = listOf("mouth")),
        VocabularyEntry(germanWords = listOf("Auge"), englishWords = listOf("eye")),
        VocabularyEntry(germanWords = listOf("Ohr"), englishWords = listOf("ear")),
        VocabularyEntry(germanWords = listOf("Nase"), englishWords = listOf("nose")),
        VocabularyEntry(germanWords = listOf("Kopf"), englishWords = listOf("head")),
        VocabularyEntry(germanWords = listOf("Haar", "Haare"), englishWords = listOf("hair")),
        VocabularyEntry(germanWords = listOf("Hand"), englishWords = listOf("hand")),
        VocabularyEntry(germanWords = listOf("Arm"), englishWords = listOf("arm")),
        VocabularyEntry(germanWords = listOf("Schulter"), englishWords = listOf("shoulder")),
        VocabularyEntry(germanWords = listOf("Fuß"), englishWords = listOf("foot", "feet (pl)")),
        VocabularyEntry(germanWords = listOf("Bein"), englishWords = listOf("leg")),
        VocabularyEntry(germanWords = listOf("Zeh"), englishWords = listOf("toe")),
        VocabularyEntry(germanWords = listOf("Wie man..."), englishWords = listOf("How to...")),
        VocabularyEntry(germanWords = listOf("besichtigen", "besuchen"), englishWords = listOf("(to) visit")),
        VocabularyEntry(germanWords = listOf("wichtig"), englishWords = listOf("important")),
        VocabularyEntry(germanWords = listOf("Seite"), englishWords = listOf("page")),
        VocabularyEntry(germanWords = listOf("was man..."), englishWords = listOf("what to...")),
        VocabularyEntry(germanWords = listOf("englischsprachig"), englishWords = listOf("English-speaking")),
        VocabularyEntry(germanWords = listOf("Lächeln"), englishWords = listOf("smile")),
        VocabularyEntry(germanWords = listOf("Entschuldigung!", "Entschuldigen Sie!"), englishWords = listOf("Excuse me")),
        VocabularyEntry(germanWords = listOf("natürlich", "selbstverständlich"), englishWords = listOf("of course")),
        VocabularyEntry(germanWords = listOf("(ein Bonbon) nehmen", "(ein Bonbon) essen"), englishWords = listOf("(to) have (a sweet)")),
        VocabularyEntry(germanWords = listOf("Bitte schön!", "Nichts zu danken!", "Gern geschehen"), englishWords = listOf("You're welcome")),
        VocabularyEntry(germanWords = listOf("Weg", "Art und Weise"), englishWords = listOf("way")),
        VocabularyEntry(germanWords = listOf("Limonade"), englishWords = listOf("Lemonade")),
        VocabularyEntry(germanWords = listOf("Stundenplan", "Fahrplan"), englishWords = listOf("timetable")),
        VocabularyEntry(germanWords = listOf("im Weg sein", "im Weg stehen"), englishWords = listOf("(to) be in the way")),
        VocabularyEntry(germanWords = listOf("Busbahnhof"), englishWords = listOf("bus station")),
        VocabularyEntry(germanWords = listOf("Person", "Mensch"), englishWords = listOf("person", "people (pl.)")),
        VocabularyEntry(germanWords = listOf("Box", "Kasten", "Schachtel", "Kiste"), englishWords = listOf("box")),
        VocabularyEntry(germanWords = listOf("öffnen", "aufmachen"), englishWords = listOf("(to) open")),
        VocabularyEntry(germanWords = listOf("Zug"), englishWords = listOf("train")),
        VocabularyEntry(germanWords = listOf("Fenster"), englishWords = listOf("window")),
        VocabularyEntry(germanWords = listOf("halten", "festhalten"), englishWords = listOf("(to) hold")),
        VocabularyEntry(germanWords = listOf("geöffnet", "offen", "aufgeschlagen"), englishWords = listOf("open")),
        VocabularyEntry(germanWords = listOf("Frau"), englishWords = listOf("woman", "women (pl.)")),
        VocabularyEntry(germanWords = listOf("Mann"), englishWords = listOf("man", "men (pl.)")),
        VocabularyEntry(germanWords = listOf("sich vordrängeln"), englishWords = listOf("(to) jump the queue")),
        VocabularyEntry(germanWords = listOf("britisch", "Brite", "Britin"), englishWords = listOf("British")),
        VocabularyEntry(germanWords = listOf("stehen"), englishWords = listOf("(to) stand")),
        VocabularyEntry(germanWords = listOf("gehen", "laufen"), englishWords = listOf("(to) walk")),
        VocabularyEntry(germanWords = listOf("Rolltreppe"), englishWords = listOf("escalator")),
        VocabularyEntry(germanWords = listOf("Schloss", "Burg"), englishWords = listOf("castle")),
        VocabularyEntry(germanWords = listOf("Flagge", "Fahne"), englishWords = listOf("flag")),
        VocabularyEntry(germanWords = listOf("Strand"), englishWords = listOf("beach")),
        VocabularyEntry(germanWords = listOf("Meer"), englishWords = listOf("sea")),
        VocabularyEntry(germanWords = listOf("kalt"), englishWords = listOf("cold")),
        VocabularyEntry(germanWords = listOf("Fels", "Stein"), englishWords = listOf("rock")),
        VocabularyEntry(germanWords = listOf("besonders", "speziell"), englishWords = listOf("special")),
        VocabularyEntry(germanWords = listOf("Form"), englishWords = listOf("shape")),
        VocabularyEntry(germanWords = listOf("viel", "viele", "eine Menge"), englishWords = listOf("a lot of")),
        VocabularyEntry(germanWords = listOf("hoch", "groß"), englishWords = listOf("high")),
        VocabularyEntry(germanWords = listOf("Berg"), englishWords = listOf("mountain")),
        VocabularyEntry(germanWords = listOf("Wald"), englishWords = listOf("forest")),
        VocabularyEntry(germanWords = listOf("Insel"), englishWords = listOf("island")),
        VocabularyEntry(germanWords = listOf("Stadtplan", "Landkarte"), englishWords = listOf("map")),
        VocabularyEntry(germanWords = listOf("nördlich", "im Norden"), englishWords = listOf("north")),
        VocabularyEntry(germanWords = listOf("Schaf"), englishWords = listOf("sheep", "sheep (pl.)")),
        VocabularyEntry(germanWords = listOf("separat", "getrennt", "verschieden"), englishWords = listOf("separate")),
        VocabularyEntry(germanWords = listOf("Museum"), englishWords = listOf("museum")),
        VocabularyEntry(germanWords = listOf("Hauptstadt"), englishWords = listOf("capital")),
        VocabularyEntry(germanWords = listOf("Großstadt", "Stadt"), englishWords = listOf("city")),
        VocabularyEntry(germanWords = listOf("Fakt", "Tatsache"), englishWords = listOf("fact")),
        VocabularyEntry(germanWords = listOf("berühmteste", "berühmtester", "berühmtestes"), englishWords = listOf("most famous")),
        VocabularyEntry(germanWords = listOf("berühmt"), englishWords = listOf("famous")),
        VocabularyEntry(germanWords = listOf("Sehenswürdigkeit", "Anblick"), englishWords = listOf("sight")),
        VocabularyEntry(germanWords = listOf("Königin"), englishWords = listOf("queen")),
        VocabularyEntry(germanWords = listOf("Fluss"), englishWords = listOf("river")),
        VocabularyEntry(germanWords = listOf("fahren", "reiten"), englishWords = listOf("(to) ride")),
        VocabularyEntry(germanWords = listOf("am interessantesten"), englishWords = listOf("most interesting")),
        VocabularyEntry(germanWords = listOf("Stadt"), englishWords = listOf("town")),
        VocabularyEntry(germanWords = listOf("nahe", "in der Nähe von"), englishWords = listOf("near")),
        VocabularyEntry(germanWords = listOf("Dorf"), englishWords = listOf("village")),
        VocabularyEntry(germanWords = listOf("Kirche"), englishWords = listOf("church")),
        VocabularyEntry(germanWords = listOf("Kino"), englishWords = listOf("cinema")),
        VocabularyEntry(germanWords = listOf("Theater"), englishWords = listOf("theatre")),
        VocabularyEntry(germanWords = listOf("Konzert"), englishWords = listOf("concert")),
    )

    val cl_5_unit_4 = listOf(
        VocabularyEntry(germanWords = listOf("kosten"), englishWords = listOf("(to) cost")),
        VocabularyEntry(germanWords = listOf("Schiff"), englishWords = listOf("ship")),
        VocabularyEntry(germanWords = listOf("hinüber", "über"), englishWords = listOf("over")),
        VocabularyEntry(germanWords = listOf("Fuß"), englishWords = listOf("foot", "feet (pl.)")),
        VocabularyEntry(germanWords = listOf("Pier", "Hafendamm"), englishWords = listOf("pier")),
        VocabularyEntry(germanWords = listOf("frei", "kostenfrei"), englishWords = listOf("free")),
        VocabularyEntry(germanWords = listOf("Wasserrutsche"), englishWords = listOf("water slide")),
        VocabularyEntry(germanWords = listOf("Freizeitzentrum"), englishWords = listOf("leisure centre")),
        VocabularyEntry(germanWords = listOf("Freizeit"), englishWords = listOf("free time")),
        VocabularyEntry(germanWords = listOf("Blick"), englishWords = listOf("look")),
        VocabularyEntry(germanWords = listOf("auf der anderen Seite von", "über", "hinüber", "herüber", "quer durch"), englishWords = listOf("across")),
        VocabularyEntry(germanWords = listOf("zusammen", "miteinander", "gemeinsam"), englishWords = listOf("together")),
        VocabularyEntry(germanWords = listOf("spannend", "aufregend"), englishWords = listOf("exciting")),
        VocabularyEntry(germanWords = listOf("am Wochenende"), englishWords = listOf("at the weekend")),
        VocabularyEntry(germanWords = listOf("Um wie viel Uhr?"), englishWords = listOf("What time?")),
        VocabularyEntry(germanWords = listOf("gut", "in Ordnung", "schön"), englishWords = listOf("fine")),
        VocabularyEntry(germanWords = listOf("Bis dann!", "Bis..."), englishWords = listOf("See you!")),
        VocabularyEntry(germanWords = listOf("schließen", "zumachen"), englishWords = listOf("(to) close")),
        VocabularyEntry(germanWords = listOf("genug", "genügend"), englishWords = listOf("enough")),
        VocabularyEntry(germanWords = listOf("auch nicht"), englishWords = listOf("not ... either")),
        VocabularyEntry(germanWords = listOf("Tschüss!"), englishWords = listOf("Bye!")),
        VocabularyEntry(germanWords = listOf("buchstabieren"), englishWords = listOf("(to) spell")),
        VocabularyEntry(germanWords = listOf("endlich", "schließlich"), englishWords = listOf("at last")),
        VocabularyEntry(germanWords = listOf("Halbschwester"), englishWords = listOf("half-sister")),
        VocabularyEntry(germanWords = listOf("Information"), englishWords = listOf("information")),
        VocabularyEntry(germanWords = listOf("alle/-s", "ganz"), englishWords = listOf("all")),
        VocabularyEntry(germanWords = listOf("hinkommen"), englishWords = listOf("(to) get there")),
        VocabularyEntry(germanWords = listOf("fahren mit..."), englishWords = listOf("(to) get by...")),
        VocabularyEntry(germanWords = listOf("uns"), englishWords = listOf("us")),
        VocabularyEntry(germanWords = listOf("antworten", "beantworten"), englishWords = listOf("(to) answer")),
        VocabularyEntry(germanWords = listOf("schlecht", "böse", "schlimm"), englishWords = listOf("bad")),
        VocabularyEntry(germanWords = listOf("(ugs.) Wetter"), englishWords = listOf("weather")),
        VocabularyEntry(germanWords = listOf("die Daumen drücken"), englishWords = listOf("(to) keep your fingers crossed")),
        VocabularyEntry(germanWords = listOf("kommen zu", "kommen nach", "erreichen"), englishWords = listOf("(to) get to")),
        VocabularyEntry(germanWords = listOf("Bus"), englishWords = listOf("bus")),
        VocabularyEntry(germanWords = listOf("reden mit"), englishWords = listOf("(to) talk to")),
        VocabularyEntry(germanWords = listOf("Touristeninformation"), englishWords = listOf("tourist information centre")),
        VocabularyEntry(germanWords = listOf("(tun) müssen"), englishWords = listOf("(to) need (to do)")),
        VocabularyEntry(germanWords = listOf("Ich weiß (es) nicht"), englishWords = listOf("I don't know")),
        VocabularyEntry(germanWords = listOf("Markt"), englishWords = listOf("market")),
        VocabularyEntry(germanWords = listOf("bekommen", "holen", "bringen"), englishWords = listOf("(to) get")),
        VocabularyEntry(germanWords = listOf("Schwein"), englishWords = listOf("pig")),
        VocabularyEntry(germanWords = listOf("Huhn"), englishWords = listOf("chicken")),
        VocabularyEntry(germanWords = listOf("Pferd"), englishWords = listOf("horse")),
        VocabularyEntry(germanWords = listOf("Lamm"), englishWords = listOf("lamb")),
        VocabularyEntry(germanWords = listOf("Schaf"), englishWords = listOf("sheep")),
        VocabularyEntry(germanWords = listOf("Kuh"), englishWords = listOf("cow")),
        VocabularyEntry(germanWords = listOf("Ziege"), englishWords = listOf("goat")),
        VocabularyEntry(germanWords = listOf("Gans"), englishWords = listOf("goose")),
        VocabularyEntry(germanWords = listOf("Ente"), englishWords = listOf("duck")),
        VocabularyEntry(germanWords = listOf("Kapitän/-in", "Mannschaftsführer"), englishWords = listOf("captain")),
        VocabularyEntry(germanWords = listOf("Schiffsjunge"), englishWords = listOf("cabin boy")),
        VocabularyEntry(germanWords = listOf("an Bord"), englishWords = listOf("aboard")),
        VocabularyEntry(germanWords = listOf("Seemann", "Matrose"), englishWords = listOf("sailor")),
        VocabularyEntry(germanWords = listOf("Besucher/-in"), englishWords = listOf("visitor")),
        VocabularyEntry(germanWords = listOf("Tee"), englishWords = listOf("tea")),
        VocabularyEntry(germanWords = listOf("geschehen", "passieren"), englishWords = listOf("(to) happen")),
        VocabularyEntry(germanWords = listOf("Land"), englishWords = listOf("land")),
        VocabularyEntry(germanWords = listOf("Sturm"), englishWords = listOf("storm")),
        VocabularyEntry(germanWords = listOf("Welle"), englishWords = listOf("wave")),
        VocabularyEntry(germanWords = listOf("Rad", "Steuerrad", "Steuer"), englishWords = listOf("wheel")),
        VocabularyEntry(germanWords = listOf("die Segel einholen"), englishWords = listOf("(to) reef the sails")),
        VocabularyEntry(germanWords = listOf("schreien", "rufen"), englishWords = listOf("(to) shout")),
        VocabularyEntry(germanWords = listOf("klettern", "besteigen", "steigen"), englishWords = listOf("(to) climb")),
        VocabularyEntry(germanWords = listOf("Takelage"), englishWords = listOf("rigging")),
        VocabularyEntry(germanWords = listOf("gefährlich"), englishWords = listOf("dangerous")),
        VocabularyEntry(germanWords = listOf("langsam"), englishWords = listOf("slow")),
        VocabularyEntry(germanWords = listOf("mutig", "tapfer"), englishWords = listOf("brave")),
        VocabularyEntry(germanWords = listOf("herunterkommen"), englishWords = listOf("(to) come down")),
        VocabularyEntry(germanWords = listOf("Schiffsoffizier", "Maat"), englishWords = listOf("mate")),
        VocabularyEntry(germanWords = listOf("trinken"), englishWords = listOf("(to) drink")),
        VocabularyEntry(germanWords = listOf("zurück"), englishWords = listOf("back")),
        VocabularyEntry(germanWords = listOf("schlagen", "treffen"), englishWords = listOf("(to) hit")),
        VocabularyEntry(germanWords = listOf("fallen", "hinfallen"), englishWords = listOf("(to) fall")),
        VocabularyEntry(germanWords = listOf("sich verbessern", "verbessern"), englishWords = listOf("(to) improve")),
        VocabularyEntry(germanWords = listOf("aufwärmen", "sich aufwärmen"), englishWords = listOf("(to) warm up")),
        VocabularyEntry(germanWords = listOf("Mund"), englishWords = listOf("mouth")),
        VocabularyEntry(germanWords = listOf("Ton", "Geräusch", "Klang"), englishWords = listOf("sound")),
        VocabularyEntry(germanWords = listOf("in Form kommen", "fit werden"), englishWords = listOf("(to) get fit")),
        VocabularyEntry(germanWords = listOf("Rhythmus"), englishWords = listOf("rhythm")),
        VocabularyEntry(germanWords = listOf("aufstehen (von einer Sitzgelegenheit)"), englishWords = listOf("(to) stand up")),
        VocabularyEntry(germanWords = listOf("Klatsch/klatscht in die Hände"), englishWords = listOf("Clap your hands")),
        VocabularyEntry(germanWords = listOf("Laut"), englishWords = listOf("loud")),
        VocabularyEntry(germanWords = listOf("sehr"), englishWords = listOf("very much")),
        VocabularyEntry(germanWords = listOf("sprechen"), englishWords = listOf("(to) speak")),
        VocabularyEntry(germanWords = listOf("klar", "deutlich"), englishWords = listOf("clear")),
        VocabularyEntry(germanWords = listOf("eine Theaterszene spielen"), englishWords = listOf("acting a scene")),
        VocabularyEntry(germanWords = listOf("schwimmen"), englishWords = listOf("(to) swim")),
        VocabularyEntry(germanWords = listOf("retten", "bergen"), englishWords = listOf("(to) save")),
        VocabularyEntry(germanWords = listOf("Rettungsring"), englishWords = listOf("lifebuoy")),
        VocabularyEntry(germanWords = listOf("Rettungsboot"), englishWords = listOf("lifeboat")),
        VocabularyEntry(germanWords = listOf("springen"), englishWords = listOf("(to) jump")),
        VocabularyEntry(germanWords = listOf("bleiben"), englishWords = listOf("(to) stay")),
        VocabularyEntry(germanWords = listOf("unrecht haben", "sich irren"), englishWords = listOf("(to) be wrong")),
        VocabularyEntry(germanWords = listOf("leid tun"), englishWords = listOf("(to) be sorry")),
        VocabularyEntry(germanWords = listOf("(hier:) ergeben"), englishWords = listOf("(to) make")),
    )

    val cl_5_unit_5 = listOf(
        VocabularyEntry(germanWords = listOf("einkaufen gehen"), englishWords = listOf("(to) go shopping")),
        VocabularyEntry(germanWords = listOf("Wie viel (kostet/kosten...)?"), englishWords = listOf("How much (is/are)...?")),
        VocabularyEntry(germanWords = listOf("Pfund (brit. Währungseinheit)"), englishWords = listOf("pound")),
        VocabularyEntry(germanWords = listOf("teuer"), englishWords = listOf("expensive")),
        VocabularyEntry(germanWords = listOf("Qualität", "Eigenschaft"), englishWords = listOf("quality")),
        VocabularyEntry(germanWords = listOf("billig", "preiswert"), englishWords = listOf("cheap")),
        VocabularyEntry(germanWords = listOf("Flasche"), englishWords = listOf("bottle")),
        VocabularyEntry(germanWords = listOf("Sonst noch was?"), englishWords = listOf("Anything else?")),
        VocabularyEntry(germanWords = listOf("Dose", "Büchse"), englishWords = listOf("can")),
        VocabularyEntry(germanWords = listOf("Cola"), englishWords = listOf("coke")),
        VocabularyEntry(germanWords = listOf("Päckchen", "Paket", "Packung"), englishWords = listOf("packet")),
        VocabularyEntry(germanWords = listOf("Das macht..."), englishWords = listOf("That's...")),
        VocabularyEntry(germanWords = listOf("Ich suche nach..."), englishWords = listOf("I'm looking for...")),
        VocabularyEntry(germanWords = listOf("Geschenk"), englishWords = listOf("present")),
        VocabularyEntry(germanWords = listOf("Armband"), englishWords = listOf("bracelet")),
        VocabularyEntry(germanWords = listOf("Sonderangebot"), englishWords = listOf("special offer")),
        VocabularyEntry(germanWords = listOf("Es kostet...", "Sie kosten..."), englishWords = listOf("It's...", "They're...")),
        VocabularyEntry(germanWords = listOf("Kleider", "Kleidung"), englishWords = listOf("clothes")),
        VocabularyEntry(germanWords = listOf("Snackbar", "Imbissstube"), englishWords = listOf("snack bar")),
        VocabularyEntry(germanWords = listOf("Schmuck"), englishWords = listOf("jewellery")),
        VocabularyEntry(germanWords = listOf("Penny", "Pence (brit. Währungseinheit)"), englishWords = listOf("penny")),
        VocabularyEntry(germanWords = listOf("Preis"), englishWords = listOf("price")),
        VocabularyEntry(germanWords = listOf("Euro (Währung)"), englishWords = listOf("euro")),
        VocabularyEntry(germanWords = listOf("Cent (Währung)"), englishWords = listOf("cent")),
        VocabularyEntry(germanWords = listOf("als Nächstes"), englishWords = listOf("next")),
        VocabularyEntry(germanWords = listOf("verkaufen"), englishWords = listOf("(to) sell")),
        VocabularyEntry(germanWords = listOf("Glas"), englishWords = listOf("glass")),
        VocabularyEntry(germanWords = listOf("Orange"), englishWords = listOf("orange")),
        VocabularyEntry(germanWords = listOf("Saft"), englishWords = listOf("juice")),
        VocabularyEntry(germanWords = listOf("im Moment", "gerade"), englishWords = listOf("at the moment")),
        VocabularyEntry(germanWords = listOf("traurig"), englishWords = listOf("sad")),
        VocabularyEntry(germanWords = listOf("verdienen"), englishWords = listOf("(to) earn")),
        VocabularyEntry(germanWords = listOf("Flohmarkt"), englishWords = listOf("flea market")),
        VocabularyEntry(germanWords = listOf("Gemeindezentrum"), englishWords = listOf("community centre")),
        VocabularyEntry(germanWords = listOf("organisieren"), englishWords = listOf("(to) organise")),
        VocabularyEntry(germanWords = listOf("Jahr", "Schuljahr"), englishWords = listOf("year")),
        VocabularyEntry(germanWords = listOf("Wohltätigkeitsverein", "wohltätige Zwecke", "Wohlfahrt"), englishWords = listOf("charity")),
        VocabularyEntry(germanWords = listOf("Spielzeug"), englishWords = listOf("toy")),
        VocabularyEntry(germanWords = listOf("ausräumen", "entrümpeln"), englishWords = listOf("(to) clear out")),
        VocabularyEntry(germanWords = listOf("Garage"), englishWords = listOf("garage")),
        VocabularyEntry(germanWords = listOf("fühlen", "sich fühlen"), englishWords = listOf("(to) feel")),
        VocabularyEntry(germanWords = listOf("hoffnungsvoll"), englishWords = listOf("hopeful")),
        VocabularyEntry(germanWords = listOf("klingeln", "läuten"), englishWords = listOf("(to) ring")),
        VocabularyEntry(germanWords = listOf("Geld verdienen"), englishWords = listOf("(to) make money")),
        VocabularyEntry(germanWords = listOf("voll (von)"), englishWords = listOf("full (of)")),
        VocabularyEntry(germanWords = listOf("wegwerfen"), englishWords = listOf("(to) throw away")),
        VocabularyEntry(germanWords = listOf("z.B. (= zum Beispiel)"), englishWords = listOf("e.g. (= for example)")),
        VocabularyEntry(germanWords = listOf("Kaffee"), englishWords = listOf("coffee")),
        VocabularyEntry(germanWords = listOf("Second-Hand-Laden (für wohltätige Zwecke)"), englishWords = listOf("charity shop")),
        VocabularyEntry(germanWords = listOf("irgendein/-e/-er", "irgendwelche"), englishWords = listOf("any")),
        VocabularyEntry(germanWords = listOf("Telefon"), englishWords = listOf("telephone")),
        VocabularyEntry(germanWords = listOf("Zu dumm!", "Schade!"), englishWords = listOf("Too bad!")),
        VocabularyEntry(germanWords = listOf("den Hund ausführen", "mit dem Hund spazieren gehen"), englishWords = listOf("(to) walk the dog")),
        VocabularyEntry(germanWords = listOf("Dafür sind Freunde da."), englishWords = listOf("That's what friends are for.")),
        VocabularyEntry(germanWords = listOf("müssen"), englishWords = listOf("must")),
        VocabularyEntry(germanWords = listOf("wert sein"), englishWords = listOf("(to) be worth")),
        VocabularyEntry(germanWords = listOf("Wie viele...?"), englishWords = listOf("How many...?")),
        VocabularyEntry(germanWords = listOf("ungefähr", "circa", "etwa"), englishWords = listOf("about")),
        VocabularyEntry(germanWords = listOf("Zeug"), englishWords = listOf("stuff")),
        VocabularyEntry(germanWords = listOf("kein/-e/-en"), englishWords = listOf("not ... any")),
        VocabularyEntry(germanWords = listOf("ein paar"), englishWords = listOf("a couple of")),
        VocabularyEntry(germanWords = listOf("alles"), englishWords = listOf("everything")),
        VocabularyEntry(germanWords = listOf("fragen nach", "bitten um"), englishWords = listOf("(to) ask for")),
        VocabularyEntry(germanWords = listOf("Schnäppchen"), englishWords = listOf("bargain")),
        VocabularyEntry(germanWords = listOf("ausgeben (Geld)"), englishWords = listOf("(to) spend")),
        VocabularyEntry(germanWords = listOf("ein wenig", "etwas"), englishWords = listOf("a little")),
        VocabularyEntry(germanWords = listOf("halten von", "denken über"), englishWords = listOf("(to) think of")),
        VocabularyEntry(germanWords = listOf("irgendetwas"), englishWords = listOf("anything")),
        VocabularyEntry(germanWords = listOf("nichts"), englishWords = listOf("nothing")),
        VocabularyEntry(germanWords = listOf("jeder (beliebige)", "irgendjemand"), englishWords = listOf("anybody")),
        VocabularyEntry(germanWords = listOf("jemand"), englishWords = listOf("somebody")),
        VocabularyEntry(germanWords = listOf("niemand"), englishWords = listOf("nobody")),
        VocabularyEntry(germanWords = listOf("jemand"), englishWords = listOf("someone")),
        VocabularyEntry(germanWords = listOf("jeder (beliebige)", "irgendjemand"), englishWords = listOf("anyone")),
        VocabularyEntry(germanWords = listOf("niemand"), englishWords = listOf("no one")),
        VocabularyEntry(germanWords = listOf("Gitarre"), englishWords = listOf("guitar")),
        VocabularyEntry(germanWords = listOf("der/die Glückliche"), englishWords = listOf("lucky ...")),
        VocabularyEntry(germanWords = listOf("Wein"), englishWords = listOf("wine")),
        VocabularyEntry(germanWords = listOf("Tombola"), englishWords = listOf("raffle")),
        VocabularyEntry(germanWords = listOf("Preis", "Gewinn"), englishWords = listOf("prize")),
        VocabularyEntry(germanWords = listOf("Los", "Ticket", "Eintrittskarte"), englishWords = listOf("ticket")),
        VocabularyEntry(germanWords = listOf("jede/r/s"), englishWords = listOf("each")),
        VocabularyEntry(germanWords = listOf("pro Person", "pro Stück"), englishWords = listOf("each")),
        VocabularyEntry(germanWords = listOf("hoffen"), englishWords = listOf("(to) hope")),
        VocabularyEntry(germanWords = listOf("glauben"), englishWords = listOf("(to) think")),
        VocabularyEntry(germanWords = listOf("noch", "immer noch"), englishWords = listOf("still")),
        VocabularyEntry(germanWords = listOf("ziehen"), englishWords = listOf("(to) pull")),
        VocabularyEntry(germanWords = listOf("Stück"), englishWords = listOf("piece")),
        VocabularyEntry(germanWords = listOf("gebrochen", "kaputt"), englishWords = listOf("broken")),
        VocabularyEntry(germanWords = listOf("entsetzt"), englishWords = listOf("horrified")),
        VocabularyEntry(germanWords = listOf("Müll", "Gerümpel"), englishWords = listOf("rubbish")),
        VocabularyEntry(germanWords = listOf("Münze"), englishWords = listOf("coin")),
        VocabularyEntry(germanWords = listOf("so ... wie"), englishWords = listOf("as ... as")),
        VocabularyEntry(germanWords = listOf("nichts"), englishWords = listOf("not ... anything")),
        VocabularyEntry(germanWords = listOf("mehr ... als"), englishWords = listOf("more ... than")),
        VocabularyEntry(germanWords = listOf("halb"), englishWords = listOf("half")),
        VocabularyEntry(germanWords = listOf("Kopf"), englishWords = listOf("head")),
        VocabularyEntry(germanWords = listOf("glauben"), englishWords = listOf("(to) believe")),
        VocabularyEntry(germanWords = listOf("umarmen"), englishWords = listOf("(to) hug")),
        VocabularyEntry(germanWords = listOf("enttäuscht"), englishWords = listOf("disappointed")),
        VocabularyEntry(germanWords = listOf("hilfsbereit", "hilfreich"), englishWords = listOf("helpful")),
        VocabularyEntry(germanWords = listOf("dankbar"), englishWords = listOf("thankful")),
        VocabularyEntry(germanWords = listOf("aufgeregt", "begeistert"), englishWords = listOf("excited")),
        VocabularyEntry(germanWords = listOf("hilflos"), englishWords = listOf("helpless")),
        VocabularyEntry(germanWords = listOf("Anrufbeantworter"), englishWords = listOf("answering machine")),
        VocabularyEntry(germanWords = listOf("Botschaft", "Nachricht"), englishWords = listOf("message")),
        VocabularyEntry(germanWords = listOf("anrufen", "rufen"), englishWords = listOf("(to) call")),
        VocabularyEntry(germanWords = listOf("eine Nachricht hinterlassen"), englishWords = listOf("(to) leave a message")),
        VocabularyEntry(germanWords = listOf("Anrufer/-in"), englishWords = listOf("caller")),
        VocabularyEntry(germanWords = listOf("Anruf", "Telefonanruf"), englishWords = listOf("phone call")),
        VocabularyEntry(germanWords = listOf("einen Anruf entgegennehmen"), englishWords = listOf("(to) answer the phone")),
        VocabularyEntry(germanWords = listOf("verbinden"), englishWords = listOf("(to) put through")),
        VocabularyEntry(germanWords = listOf("übrig"), englishWords = listOf("left")),
        VocabularyEntry(germanWords = listOf("Ich möchte...", "Ich würde gerne..."), englishWords = listOf("I'd like to...", "I would like to")),
        VocabularyEntry(germanWords = listOf("eine Nachricht entgegennehmen", "jmdm. etw. ausrichten"), englishWords = listOf("(to) take a message")),
        VocabularyEntry(germanWords = listOf("Ich hole sie/ihn"), englishWords = listOf("I'll get her/him")),
        VocabularyEntry(germanWords = listOf("einrichten", "aufbauen"), englishWords = listOf("(to) set up")),
        VocabularyEntry(germanWords = listOf("Wörterbuch"), englishWords = listOf("dictionary")),
        VocabularyEntry(germanWords = listOf("Käufer/-in"), englishWords = listOf("buyer")),
        VocabularyEntry(germanWords = listOf("Verkäufer/-in (auf einem Flohmarkt)"), englishWords = listOf("seller")),
        VocabularyEntry(germanWords = listOf("die Hälfte"), englishWords = listOf("half", "halves (pl.) (of)")),
        VocabularyEntry(germanWords = listOf("Tor", "Ziel"), englishWords = listOf("goal")),
    )

    val cl_5_unit_6 = listOf(
        VocabularyEntry(germanWords = listOf("Kostüm"), englishWords = listOf("costume")),
        VocabularyEntry(germanWords = listOf("zur selben Zeit", "gleichzeitig"), englishWords = listOf("at the same time")),
        VocabularyEntry(germanWords = listOf("Bowlingbahn"), englishWords = listOf("bowling alley")),
        VocabularyEntry(germanWords = listOf("hochleben lassen"), englishWords = listOf("(to) give the bumps")),
        VocabularyEntry(germanWords = listOf("feiern"), englishWords = listOf("(to) celebrate")),
        VocabularyEntry(germanWords = listOf("Geburtstag"), englishWords = listOf("birthday")),
        VocabularyEntry(germanWords = listOf("Eisbahn", "Schlittschuhbahn"), englishWords = listOf("ice rink")),
        VocabularyEntry(germanWords = listOf("ausblasen", "auspusten"), englishWords = listOf("(to) blow out")),
        VocabularyEntry(germanWords = listOf("Kerze"), englishWords = listOf("candle")),
        VocabularyEntry(germanWords = listOf("sich etwas wünschen"), englishWords = listOf("(to) make a wish")),
        VocabularyEntry(germanWords = listOf("Wunsch"), englishWords = listOf("wish")),
        VocabularyEntry(germanWords = listOf("Alles Gute zum Geburtstag!", "Herzlichen Glückwunsch zum Geburtstag!"), englishWords = listOf("Happy Birthday")),
        VocabularyEntry(germanWords = listOf("Datum"), englishWords = listOf("date")),
        VocabularyEntry(germanWords = listOf("Frühling"), englishWords = listOf("spring")),
        VocabularyEntry(germanWords = listOf("Sommer"), englishWords = listOf("summer")),
        VocabularyEntry(germanWords = listOf("Herbst"), englishWords = listOf("autumn")),
        VocabularyEntry(germanWords = listOf("Winter"), englishWords = listOf("winter")),
        VocabularyEntry(germanWords = listOf("Teil", "Stadtteil"), englishWords = listOf("part")),
        VocabularyEntry(germanWords = listOf("Kultur"), englishWords = listOf("culture")),
        VocabularyEntry(germanWords = listOf("schnell"), englishWords = listOf("quick")),
        VocabularyEntry(germanWords = listOf("Wettkampf", "Wettbewerb"), englishWords = listOf("contest")),
        VocabularyEntry(germanWords = listOf("Schinkenspeck", "Speck"), englishWords = listOf("bacon")),
        VocabularyEntry(germanWords = listOf("Brot"), englishWords = listOf("bread")),
        VocabularyEntry(germanWords = listOf("Kuchen", "Torte"), englishWords = listOf("cake")),
        VocabularyEntry(germanWords = listOf("Ei"), englishWords = listOf("egg")),
        VocabularyEntry(germanWords = listOf("Fisch"), englishWords = listOf("fish", "fish (pl.)")),
        VocabularyEntry(germanWords = listOf("Frucht", "Obst"), englishWords = listOf("fruit")),
        VocabularyEntry(germanWords = listOf("Kuchen", "Pastete"), englishWords = listOf("pie")),
        VocabularyEntry(germanWords = listOf("fremd", "seltsam", "merkwürdig"), englishWords = listOf("strange")),
        VocabularyEntry(germanWords = listOf("Apfel"), englishWords = listOf("apple")),
        VocabularyEntry(germanWords = listOf("Butter"), englishWords = listOf("butter")),
        VocabularyEntry(germanWords = listOf("Frühstückszerealie", "Getreideprodukt (z.B. Cornflakes oder Müsli)"), englishWords = listOf("cereal")),
        VocabularyEntry(germanWords = listOf("Schokolade"), englishWords = listOf("chocolate")),
        VocabularyEntry(germanWords = listOf("Kartoffelchip"), englishWords = listOf("crisp")),
        VocabularyEntry(germanWords = listOf("Schinken"), englishWords = listOf("ham")),
        VocabularyEntry(germanWords = listOf("Nuss"), englishWords = listOf("nut")),
        VocabularyEntry(germanWords = listOf("Pflaume"), englishWords = listOf("plum")),
        VocabularyEntry(germanWords = listOf("Erdbeere"), englishWords = listOf("strawberry", "strawberries (pl.)")),
        VocabularyEntry(germanWords = listOf("süß"), englishWords = listOf("sweet")),
        VocabularyEntry(germanWords = listOf("gesund"), englishWords = listOf("healthy")),
        VocabularyEntry(germanWords = listOf("heiß"), englishWords = listOf("hot")),
        VocabularyEntry(germanWords = listOf("Supermarkt"), englishWords = listOf("supermarket")),
        VocabularyEntry(germanWords = listOf("zueinander passen", "zueinander gehören"), englishWords = listOf("(to) go together")),
        VocabularyEntry(germanWords = listOf("weiße Bohnen in Tomatensoße"), englishWords = listOf("baked beans (pl.)")),
        VocabularyEntry(germanWords = listOf("Banane"), englishWords = listOf("banana")),
        VocabularyEntry(germanWords = listOf("Fertiggericht"), englishWords = listOf("ready meal")),
        VocabularyEntry(germanWords = listOf("Salat"), englishWords = listOf("salad")),
        VocabularyEntry(germanWords = listOf("Inder/-in", "indisch"), englishWords = listOf("Indian")),
        VocabularyEntry(germanWords = listOf("indisches Hähnchengericht"), englishWords = listOf("chicken tikka masala")),
        VocabularyEntry(germanWords = listOf("Milch"), englishWords = listOf("milk")),
        VocabularyEntry(germanWords = listOf("jung"), englishWords = listOf("young")),
        VocabularyEntry(germanWords = listOf("schiefgehen"), englishWords = listOf("(to) go wrong")),
        VocabularyEntry(germanWords = listOf("schließlich", "zum Schluss"), englishWords = listOf("in the end")),
        VocabularyEntry(germanWords = listOf("stolpern (über)"), englishWords = listOf("(to) trip (over)")),
        VocabularyEntry(germanWords = listOf("verletzen", "weh tun"), englishWords = listOf("(to) hurt")),
        VocabularyEntry(germanWords = listOf("lecker"), englishWords = listOf("yummy")),
        VocabularyEntry(germanWords = listOf("Pech", "Unglück"), englishWords = listOf("bad luck")),
        VocabularyEntry(germanWords = listOf("Monat"), englishWords = listOf("month")),
        VocabularyEntry(germanWords = listOf("gestern"), englishWords = listOf("yesterday")),
        VocabularyEntry(germanWords = listOf("Postkarte"), englishWords = listOf("postcard")),
        VocabularyEntry(germanWords = listOf("Ferien", "Urlaub"), englishWords = listOf("vacation (AE)")),
        VocabularyEntry(germanWords = listOf("Grill", "Grillparty"), englishWords = listOf("barbecue")),
        VocabularyEntry(germanWords = listOf("Feuerwerk"), englishWords = listOf("fireworks (pl.)")),
        VocabularyEntry(germanWords = listOf("super", "spitze", "beeindruckend"), englishWords = listOf("awesome")),
        VocabularyEntry(germanWords = listOf("normal"), englishWords = listOf("normal")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("yard (AE)")),
        VocabularyEntry(germanWords = listOf("Keks"), englishWords = listOf("cookie (AE)")),
        VocabularyEntry(germanWords = listOf("Pommes Frites"), englishWords = listOf("fries (pl.) (AE)")),
        VocabularyEntry(germanWords = listOf("Süßigkeiten"), englishWords = listOf("candy (AE)")),
        VocabularyEntry(germanWords = listOf("Typ", "Kerl", "Leute (pl.)"), englishWords = listOf("guy")),
        VocabularyEntry(germanWords = listOf("wollen, dass jemand etwas tut"), englishWords = listOf("(to) want somebody to do something")),
        VocabularyEntry(germanWords = listOf("Pfannkuchen"), englishWords = listOf("pancake")),
        VocabularyEntry(germanWords = listOf("statt", "anstatt", "an Stelle von"), englishWords = listOf("instead of")),
        VocabularyEntry(germanWords = listOf("Weihnachten"), englishWords = listOf("Christmas")),
        VocabularyEntry(germanWords = listOf("Ostern"), englishWords = listOf("Easter")),
        VocabularyEntry(germanWords = listOf("Silvester"), englishWords = listOf("New Year's Eve")),
        VocabularyEntry(germanWords = listOf("aufbleiben"), englishWords = listOf("(to) stay up")),
        VocabularyEntry(germanWords = listOf("Mitternacht"), englishWords = listOf("midnight")),
        VocabularyEntry(germanWords = listOf("vor (zeitlich)"), englishWords = listOf("ago")),
        VocabularyEntry(germanWords = listOf("Ferien"), englishWords = listOf("holidays", "vacation")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden", "yard")),
        VocabularyEntry(germanWords = listOf("Keks"), englishWords = listOf("biscuit", "cookie")),
        VocabularyEntry(germanWords = listOf("Pommes frites"), englishWords = listOf("chips", "fries")),
        VocabularyEntry(germanWords = listOf("Süßigkeiten"), englishWords = listOf("sweets", "candy")),
        VocabularyEntry(germanWords = listOf("Fußball"), englishWords = listOf("football", "soccer")),
        VocabularyEntry(germanWords = listOf("Farbe"), englishWords = listOf("colour", "color")),
        VocabularyEntry(germanWords = listOf("Lieblings-"), englishWords = listOf("favourite", "favorite")),
        VocabularyEntry(germanWords = listOf("Zentrum"), englishWords = listOf("centre", "center")),
        VocabularyEntry(germanWords = listOf("Theater"), englishWords = listOf("theatre", "theater")),
        VocabularyEntry(germanWords = listOf("Mama"), englishWords = listOf("mum", "mom")),
        VocabularyEntry(germanWords = listOf("1. April"), englishWords = listOf("1st April", "April 1st")),
        VocabularyEntry(germanWords = listOf("4. Juli"), englishWords = listOf("4th July", "July 4th")),
        VocabularyEntry(germanWords = listOf("plötzlich", "auf einmal"), englishWords = listOf("suddenly")),
        VocabularyEntry(germanWords = listOf("zählen (auf)"), englishWords = listOf("(to) count (on)")),
        VocabularyEntry(germanWords = listOf("flüstern"), englishWords = listOf("(to) whisper")),
        VocabularyEntry(germanWords = listOf("Wie geht es dir?", "Wie geht es euch?", "Wie geht es Ihnen?"), englishWords = listOf("How are you?")),
        VocabularyEntry(germanWords = listOf("lächeln"), englishWords = listOf("(to) smile")),
        VocabularyEntry(germanWords = listOf("sich beeilen", "eilen"), englishWords = listOf("(to) hurry")),
        VocabularyEntry(germanWords = listOf("einsam"), englishWords = listOf("lonely")),
        VocabularyEntry(germanWords = listOf("gelangweilt"), englishWords = listOf("bored")),
        VocabularyEntry(germanWords = listOf("Pech haben"), englishWords = listOf("(to) be unlucky")),
        VocabularyEntry(germanWords = listOf("einsteigen", "hineingelangen"), englishWords = listOf("(to) get into")),
        VocabularyEntry(germanWords = listOf("hungrig"), englishWords = listOf("hungry")),
        VocabularyEntry(germanWords = listOf("besser", "lieber"), englishWords = listOf("better")),
        VocabularyEntry(germanWords = listOf("innen", "im Innern", "hinein nach drinnen", "in", "drin"), englishWords = listOf("inside")),
        VocabularyEntry(germanWords = listOf("doch", "schließlich", "immerhin"), englishWords = listOf("after all")),
        VocabularyEntry(germanWords = listOf("Erde", "Welt"), englishWords = listOf("world")),
        VocabularyEntry(germanWords = listOf("Art", "Sorte"), englishWords = listOf("kind")),
        VocabularyEntry(germanWords = listOf("wie"), englishWords = listOf("as")),
        VocabularyEntry(germanWords = listOf("Freundschaften schließen"), englishWords = listOf("(to) make friends")),
        VocabularyEntry(germanWords = listOf("unabhängig"), englishWords = listOf("independent")),
        VocabularyEntry(germanWords = listOf("amerikanisch", "aus Amerika", "Amerikaner/-in"), englishWords = listOf("American")),
        VocabularyEntry(germanWords = listOf("Regierung"), englishWords = listOf("government")),
        VocabularyEntry(germanWords = listOf("Amtssprache"), englishWords = listOf("official language")),
        VocabularyEntry(germanWords = listOf("überall", "rundherum", "rings umher"), englishWords = listOf("all around")),
        VocabularyEntry(germanWords = listOf("Million"), englishWords = listOf("million")),
        VocabularyEntry(germanWords = listOf("Technologie"), englishWords = listOf("technology")),
        VocabularyEntry(germanWords = listOf("kommunizieren", "sich verständigen"), englishWords = listOf("communicate")),
        VocabularyEntry(germanWords = listOf("obwohl"), englishWords = listOf("although")),
        VocabularyEntry(germanWords = listOf("nicht mehr"), englishWords = listOf("not any more")),
        VocabularyEntry(germanWords = listOf("die USA", "die Vereinigten Staaten von Amerika"), englishWords = listOf("the USA", "United States of America")),
        VocabularyEntry(germanWords = listOf("was sonst", "was noch"), englishWords = listOf("what else")),
        VocabularyEntry(germanWords = listOf("Ereignis", "Veranstaltung"), englishWords = listOf("event")),
        VocabularyEntry(germanWords = listOf("Tradition"), englishWords = listOf("tradition")),
        VocabularyEntry(germanWords = listOf("religiös", "gläubig"), englishWords = listOf("religious")),
        VocabularyEntry(germanWords = listOf("national", "landesweit"), englishWords = listOf("national")),
        VocabularyEntry(germanWords = listOf("Hochzeit"), englishWords = listOf("wedding")),
        VocabularyEntry(germanWords = listOf("historisch", "geschichtlich"), englishWords = listOf("historical")),
        VocabularyEntry(germanWords = listOf("königlich"), englishWords = listOf("royal")),
        VocabularyEntry(germanWords = listOf("überall (in)"), englishWords = listOf("all over")),
        VocabularyEntry(germanWords = listOf("Lagerfeuer", "Freudenfeuer"), englishWords = listOf("bonfire")),
        VocabularyEntry(germanWords = listOf("Hintergrund"), englishWords = listOf("background")),
        VocabularyEntry(germanWords = listOf("Rolle"), englishWords = listOf("role")),
        VocabularyEntry(germanWords = listOf("ein/-e andere/-r/-s", "noch ein/-e"), englishWords = listOf("another")),
        VocabularyEntry(germanWords = listOf("Tausende (von)"), englishWords = listOf("thousands of")),
        VocabularyEntry(germanWords = listOf("Londoner/-in"), englishWords = listOf("Londoner")),
        VocabularyEntry(germanWords = listOf("ganz"), englishWords = listOf("whole")),
        VocabularyEntry(germanWords = listOf("international"), englishWords = listOf("international")),
        VocabularyEntry(germanWords = listOf("ernsthaft", "ernst"), englishWords = listOf("serious")),
        VocabularyEntry(germanWords = listOf("farbenfroh", "bunt"), englishWords = listOf("colourful")),
        VocabularyEntry(germanWords = listOf("christlich"), englishWords = listOf("Christian")),
        VocabularyEntry(germanWords = listOf("Stadion"), englishWords = listOf("stadium")),
        VocabularyEntry(germanWords = listOf("entlang", "herunter", "hinunter"), englishWords = listOf("down")),
        VocabularyEntry(germanWords = listOf("Meile (brit. und amerikan. Längenmaß)"), englishWords = listOf("mile")),
        VocabularyEntry(germanWords = listOf("bis zu"), englishWords = listOf("up to")),
        VocabularyEntry(germanWords = listOf("Boden", "unterer Teil", "Grund"), englishWords = listOf("bottom")),
        VocabularyEntry(germanWords = listOf("Alligator"), englishWords = listOf("alligator")),
        VocabularyEntry(germanWords = listOf("Ureinwohner/-in Amerikas", "Indianer/-in", "indianisch"), englishWords = listOf("Native American")),
        VocabularyEntry(germanWords = listOf("Areal", "Gebiet", "Fläche"), englishWords = listOf("area")),
        VocabularyEntry(germanWords = listOf("bedeuten"), englishWords = listOf("(to) mean")),
        VocabularyEntry(germanWords = listOf("werden"), englishWords = listOf("(to) become")),
        VocabularyEntry(germanWords = listOf("Staat", "Bundesstaat", "Land"), englishWords = listOf("state")),
        VocabularyEntry(germanWords = listOf("Messe", "Jahrmarkt"), englishWords = listOf("fair")),
        VocabularyEntry(germanWords = listOf("Kuh"), englishWords = listOf("cow")),
        VocabularyEntry(germanWords = listOf("auch"), englishWords = listOf("also")),
        VocabularyEntry(germanWords = listOf("bestehen aus"), englishWords = listOf("(to) be made up of")),
        VocabularyEntry(germanWords = listOf("Eisbär"), englishWords = listOf("polar bear")),
        VocabularyEntry(germanWords = listOf("anbauen", "züchten"), englishWords = listOf("(to) grow")),
        VocabularyEntry(germanWords = listOf("herstellen", "produzieren"), englishWords = listOf("(to) produce")),
        VocabularyEntry(germanWords = listOf("Küste"), englishWords = listOf("coast")),
        VocabularyEntry(germanWords = listOf("benannt sein nach"), englishWords = listOf("(to) be named after")),
        VocabularyEntry(germanWords = listOf("Präsident/-in"), englishWords = listOf("president")),
        VocabularyEntry(germanWords = listOf("Monument", "Denkmal"), englishWords = listOf("monument")),
        VocabularyEntry(germanWords = listOf("Mond"), englishWords = listOf("moon")),
        VocabularyEntry(germanWords = listOf("Raum", "Weltraum"), englishWords = listOf("space")),
        VocabularyEntry(germanWords = listOf("Wolkenkratzer"), englishWords = listOf("skyscraper")),
        VocabularyEntry(germanWords = listOf("Zoo", "Tierpark"), englishWords = listOf("zoo")),
        VocabularyEntry(germanWords = listOf("die Franzosen"), englishWords = listOf("the French")),
        VocabularyEntry(germanWords = listOf("Freiheit", "Unabhängigkeit"), englishWords = listOf("freedom")),
        VocabularyEntry(germanWords = listOf("genießen", "sich freuen an"), englishWords = listOf("(to) enjoy")),
        VocabularyEntry(germanWords = listOf("Dollarnote", "Dollarschein"), englishWords = listOf("dollar bill")),
        VocabularyEntry(germanWords = listOf("Korn", "Mais", "Getreide"), englishWords = listOf("corn")),
        VocabularyEntry(germanWords = listOf("Weizen"), englishWords = listOf("wheat")),
        VocabularyEntry(germanWords = listOf("Baumwolle"), englishWords = listOf("cotton")),
        VocabularyEntry(germanWords = listOf("Holz"), englishWords = listOf("wood")),
        VocabularyEntry(germanWords = listOf("Pfirsich"), englishWords = listOf("peach")),
        VocabularyEntry(germanWords = listOf("Feld", "Wiese", "Weide", "Acker"), englishWords = listOf("field")),
        VocabularyEntry(germanWords = listOf("Viehzuchtbetrieb"), englishWords = listOf("cattle farm")),
        VocabularyEntry(germanWords = listOf("Kaktus"), englishWords = listOf("cactus")),
        VocabularyEntry(germanWords = listOf("Wüste"), englishWords = listOf("desert")),
        VocabularyEntry(germanWords = listOf("Wasserfall"), englishWords = listOf("waterfall")),
        VocabularyEntry(germanWords = listOf("Fabrik", "Werk"), englishWords = listOf("factory")),
        VocabularyEntry(germanWords = listOf("Flugzeug"), englishWords = listOf("airplane")),
        VocabularyEntry(germanWords = listOf("Rakete"), englishWords = listOf("rocket"))
    )
}