package com.example.vokabeltrainer // Stelle sicher, dass der Paketname korrekt ist

// Datenklasse für Vokabeleinträge (kann auch hier bleiben oder in einer eigenen Datei sein)
data class VocabularyEntry(
    val germanWords: List<String>,
    val englishWords: List<String>
)

object VocabularyData {
    val unit_1 = listOf(
        VocabularyEntry(germanWords = listOf("Hund", ), englishWords = listOf("dog")),
        VocabularyEntry(germanWords = listOf("Maus"), englishWords = listOf("mice")),
        VocabularyEntry(germanWords = listOf("Ball"), englishWords = listOf("ball")),
        VocabularyEntry(germanWords = listOf("verschieden", "unterschiedlich"), englishWords = listOf("different")),
        VocabularyEntry(germanWords = listOf("knapp", "geschlossen"), englishWords = listOf("close")),
        VocabularyEntry(germanWords = listOf("See"), englishWords = listOf("lake")),
        VocabularyEntry(germanWords = listOf("Boot"), englishWords = listOf("boat")),
        VocabularyEntry(germanWords = listOf("Rätsel"), englishWords = listOf("puzzle")),
        VocabularyEntry(germanWords = listOf("Angst haben", "sich fürchten"), englishWords = listOf("scared")),
        VocabularyEntry(germanWords = listOf("Freund"), englishWords = listOf("friend")),
        VocabularyEntry(germanWords = listOf("Wort"), englishWords = listOf("word")),
        VocabularyEntry(germanWords = listOf("essen"), englishWords = listOf("eat")),
        VocabularyEntry(germanWords = listOf("derselbe", "der gleiche"), englishWords = listOf("the same")),
        VocabularyEntry(germanWords = listOf("deutsch"), englishWords = listOf("German")),
        VocabularyEntry(germanWords = listOf("rot"), englishWords = listOf("red")),
        VocabularyEntry(germanWords = listOf("grün"), englishWords = listOf("green")),
        VocabularyEntry(germanWords = listOf("gelb"), englishWords = listOf("yellow")),
        VocabularyEntry(germanWords = listOf("blau"), englishWords = listOf("blue")),
        VocabularyEntry(germanWords = listOf("grau"), englishWords = listOf("grey")),
        VocabularyEntry(germanWords = listOf("schwarz"), englishWords = listOf("black")),
        VocabularyEntry(germanWords = listOf("weis"), englishWords = listOf("white")),
        VocabularyEntry(germanWords = listOf("orange"), englishWords = listOf("orange")),
        VocabularyEntry(germanWords = listOf("Lila"), englishWords = listOf("purple")),
        VocabularyEntry(germanWords = listOf("braun"), englishWords = listOf("brown")),
        VocabularyEntry(germanWords = listOf("pink"), englishWords = listOf("pink")),
        VocabularyEntry(germanWords = listOf("null", "0"), englishWords = listOf("zero")),
        VocabularyEntry(germanWords = listOf("eins", "1"), englishWords = listOf("one")),
        VocabularyEntry(germanWords = listOf("zwei", "2"), englishWords = listOf("two")),
        VocabularyEntry(germanWords = listOf("drei", "3"), englishWords = listOf("three")),
        VocabularyEntry(germanWords = listOf("vier", "4"), englishWords = listOf("four")),
        VocabularyEntry(germanWords = listOf("fünf", "5"), englishWords = listOf("five")),
        VocabularyEntry(germanWords = listOf("sechs", "6"), englishWords = listOf("six")),
        VocabularyEntry(germanWords = listOf("sieben", "7"), englishWords = listOf("seven")),
        VocabularyEntry(germanWords = listOf("acht", "8"), englishWords = listOf("eight")),
        VocabularyEntry(germanWords = listOf("neun", "9"), englishWords = listOf("nine")),
        VocabularyEntry(germanWords = listOf("zehn", "10"), englishWords = listOf("ten")),
        VocabularyEntry(germanWords = listOf("elf", "11"), englishWords = listOf("eleven")),
        VocabularyEntry(germanWords = listOf("zwölf", "12"), englishWords = listOf("twelve")),
        VocabularyEntry(germanWords = listOf("zu Hause"), englishWords = listOf("at home")),
        VocabularyEntry(germanWords = listOf("Familie"), englishWords = listOf("family")),
        VocabularyEntry(germanWords = listOf("wohnen", "leben"), englishWords = listOf("to live")),
        VocabularyEntry(germanWords = listOf("Wohnung"), englishWords = listOf("flat")),
        VocabularyEntry(germanWords = listOf("in der Straße", "auf der Straße"), englishWords = listOf("in the street")),
        VocabularyEntry(germanWords = listOf("Haus"), englishWords = listOf("house")),
        VocabularyEntry(germanWords = listOf("Tür"), englishWords = listOf("door")),
        VocabularyEntry(germanWords = listOf("Fernsehen", "Fernseher"), englishWords = listOf("TV", "television")),
        VocabularyEntry(germanWords = listOf("Stuhl", "Sessel"), englishWords = listOf("chair")),
        VocabularyEntry(germanWords = listOf("Tisch"), englishWords = listOf("table")),
        VocabularyEntry(germanWords = listOf("Dusche"), englishWords = listOf("shower")),
        VocabularyEntry(germanWords = listOf("Bad", "Badewanne"), englishWords = listOf("bath")),
        VocabularyEntry(germanWords = listOf("Toilette"), englishWords = listOf("toilet")),
        VocabularyEntry(germanWords = listOf("Bett"), englishWords = listOf("bed")),
        VocabularyEntry(germanWords = listOf("Uhr"), englishWords = listOf("clock")),
        VocabularyEntry(germanWords = listOf("Kleiderschrank"), englishWords = listOf("wardrobe")),
        VocabularyEntry(germanWords = listOf("Küchenschrank", "Schrank"), englishWords = listOf("cupboard")),
        VocabularyEntry(germanWords = listOf("Herd"), englishWords = listOf("cooker")),
        VocabularyEntry(germanWords = listOf("Wohnzimmer"), englishWords = listOf("living room")),
        VocabularyEntry(germanWords = listOf("Schlafzimmer"), englishWords = listOf("bedroom")),
        VocabularyEntry(germanWords = listOf("Küche"), englishWords = listOf("kitchen")),
        VocabularyEntry(germanWords = listOf("Bad", "Badezimmer"), englishWords = listOf("bathroom")),
        VocabularyEntry(germanWords = listOf("gut"), englishWords = listOf("good")),
        VocabularyEntry(germanWords = listOf("Keks"), englishWords = listOf("biscuit")),
        VocabularyEntry(germanWords = listOf("unter"), englishWords = listOf("under")),
        VocabularyEntry(germanWords = listOf("helfen"), englishWords = listOf("help")),
        VocabularyEntry(germanWords = listOf("sammeln"), englishWords = listOf("collect")),
        VocabularyEntry(germanWords = listOf("neu"), englishWords = listOf("new")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small")),
        VocabularyEntry(germanWords = listOf("Schwester"), englishWords = listOf("sister")),
        VocabularyEntry(germanWords = listOf("Bruder"), englishWords = listOf("brother")),
        VocabularyEntry(germanWords = listOf("Vater"), englishWords = listOf("father")),
        VocabularyEntry(germanWords = listOf("Mutter"), englishWords = listOf("mother")),
        VocabularyEntry(germanWords = listOf("Cousin", "Cousine"), englishWords = listOf("cousin")),
        VocabularyEntry(germanWords = listOf("ein", "eine"), englishWords = listOf("an", "a")),
        VocabularyEntry(germanWords = listOf("Einzelkind"), englishWords = listOf("only child")),
        VocabularyEntry(germanWords = listOf("Papa"), englishWords = listOf("dad")),
        VocabularyEntry(germanWords = listOf("sie ist"), englishWords = listOf("she's")),
        VocabularyEntry(germanWords = listOf("ist nicht"), englishWords = listOf("isn't", "is not")),
        VocabularyEntry(germanWords = listOf("immer", "ständig"), englishWords = listOf("always")),
        VocabularyEntry(germanWords = listOf("einfach", "leicht"), englishWords = listOf("easy")),
        VocabularyEntry(germanWords = listOf("er ist"), englishWords = listOf("he's")),
        VocabularyEntry(germanWords = listOf("Mama"), englishWords = listOf("mum")),
        VocabularyEntry(germanWords = listOf("Onkel"), englishWords = listOf("uncle")),
        VocabularyEntry(germanWords = listOf("Tante"), englishWords = listOf("aunt")),
        VocabularyEntry(germanWords = listOf("Opa"), englishWords = listOf("grandad")),
        VocabularyEntry(germanWords = listOf("Oma"), englishWords = listOf("grandma")),
        VocabularyEntry(germanWords = listOf("Stammbaum"), englishWords = listOf("family tree")),
        VocabularyEntry(germanWords = listOf("Erzähle mir von"), englishWords = listOf("Tell me about")),
        VocabularyEntry(germanWords = listOf("Meerschweinchen"), englishWords = listOf("guinea pig")),
        VocabularyEntry(germanWords = listOf("still", "ruhig", "leise"), englishWords = listOf("quiet")),
        VocabularyEntry(germanWords = listOf("Sprache"), englishWords = listOf("language")),
        VocabularyEntry(germanWords = listOf("erst", "bloß", "nur"), englishWords = listOf("only")),
        VocabularyEntry(germanWords = listOf("falsch"), englishWords = listOf("wrong")),
        VocabularyEntry(germanWords = listOf("Danke"), englishWords = listOf("Thanks")),
        VocabularyEntry(germanWords = listOf("sehr"), englishWords = listOf("very")),
        VocabularyEntry(germanWords = listOf("einige", "ein paar", "etwas"), englishWords = listOf("some")),
        VocabularyEntry(germanWords = listOf("von"), englishWords = listOf("of")),
        VocabularyEntry(germanWords = listOf("grüßen", "Grüße ausrichten"), englishWords = listOf("to say hello")),
        VocabularyEntry(germanWords = listOf("zu", "nach", "auf", "in"), englishWords = listOf("to")),
        VocabularyEntry(germanWords = listOf("nett"), englishWords = listOf("nice")),
        VocabularyEntry(germanWords = listOf("cool"), englishWords = listOf("cool")),
        VocabularyEntry(germanWords = listOf("großartig"), englishWords = listOf("great")),
        VocabularyEntry(germanWords = listOf("witzig"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in Ordnung"), englishWords = listOf("OK")),
        VocabularyEntry(germanWords = listOf("verrückt"), englishWords = listOf("crazy")),
        VocabularyEntry(germanWords = listOf("ruhig"), englishWords = listOf("quiet")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small")),
        VocabularyEntry(germanWords = listOf("groß"), englishWords = listOf("tall")),
        VocabularyEntry(germanWords = listOf("freundlich"), englishWords = listOf("friendly")),
        VocabularyEntry(germanWords = listOf("schlau"), englishWords = listOf("clever")),
        VocabularyEntry(germanWords = listOf("albern", "dumm"), englishWords = listOf("silly")),
        VocabularyEntry(germanWords = listOf("laut"), englishWords = listOf("noisy")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("short")),
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
        VocabularyEntry(germanWords = listOf("da ist/sind", "es gibt"), englishWords = listOf("there is/are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("nett"), englishWords = listOf("nice")),
        VocabularyEntry(germanWords = listOf("cool"), englishWords = listOf("cool")),
        VocabularyEntry(germanWords = listOf("großartig"), englishWords = listOf("great")),
        VocabularyEntry(germanWords = listOf("witzig"), englishWords = listOf("fun")),
        VocabularyEntry(germanWords = listOf("in Ordnung"), englishWords = listOf("OK")),
        VocabularyEntry(germanWords = listOf("verrückt"), englishWords = listOf("crazy")),
        VocabularyEntry(germanWords = listOf("klein"), englishWords = listOf("small", "little")),
        VocabularyEntry(germanWords = listOf("groß"), englishWords = listOf("tall")),
        VocabularyEntry(germanWords = listOf("freundlich"), englishWords = listOf("friendly")),
    )

    val this_is_my_room = listOf(
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
         VocabularyEntry(germanWords = listOf("das ist/sind", "es gibt"), englishWords = listOf("there is/are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("Herr (Anrede)"), englishWords = listOf("Mr")),
        VocabularyEntry(germanWords = listOf("Frau (Anrede)"), englishWords = listOf("Mrs")),
        VocabularyEntry(germanWords = listOf("jetzt", "nun"), englishWords = listOf("now")),
        VocabularyEntry(germanWords = listOf("Auto"), englishWords = listOf("car")),
        VocabularyEntry(germanWords = listOf("überall", "überallhin"), englishWords = listOf("everywhere")),
        VocabularyEntry(germanWords = listOf("wieder", "noch einmal", "noch mal"), englishWords = listOf("again")),
        VocabularyEntry(germanWords = listOf("Fußboden"), englishWords = listOf("floor")),
        VocabularyEntry(germanWords = listOf("neben"), englishWords = listOf("next to")),
        VocabularyEntry(germanWords = listOf("vor"), englishWords = listOf("in front of")),
        VocabularyEntry(germanWords = listOf("zuhören", "anhören"), englishWords = listOf("listen (to)")),
        VocabularyEntry(germanWords = listOf("Idee", "Einfall"), englishWords = listOf("idea")),
        VocabularyEntry(germanWords = listOf("Dachboden"), englishWords = listOf("loft")),
        VocabularyEntry(germanWords = listOf("eigene/r/s"), englishWords = listOf("own")),
        VocabularyEntry(germanWords = listOf("Kleiderschrank"), englishWords = listOf("wardrobe")),
        VocabularyEntry(germanWords = listOf("Bett"), englishWords = listOf("bed")),
        VocabularyEntry(germanWords = listOf("Tisch"), englishWords = listOf("table")),
        VocabularyEntry(germanWords = listOf("Stuhl"), englishWords = listOf("chair")),
        VocabularyEntry(germanWords = listOf("Lampe"), englishWords = listOf("lamp")),
        VocabularyEntry(germanWords = listOf("Spiegel"), englishWords = listOf("mirror")),
        VocabularyEntry(germanWords = listOf("Regal", "Regale"), englishWords = listOf("shelf", "shelves")),
        VocabularyEntry(germanWords = listOf("Teppich", "Vorleger"), englishWords = listOf("rug")),
        VocabularyEntry(germanWords = listOf("Gitarre"), englishWords = listOf("guitar")),
        VocabularyEntry(germanWords = listOf("Skateboard"), englishWords = listOf("skateboard")),
        VocabularyEntry(germanWords = listOf("Poster"), englishWords = listOf("poster")),
        VocabularyEntry(germanWords = listOf("Spielzeug"), englishWords = listOf("toy")),
        VocabularyEntry(germanWords = listOf("Stofftier", "Stofftierchen"), englishWords = listOf("cuddly toy")),
        VocabularyEntry(germanWords = listOf("Computer"), englishWords = listOf("computer")),
    )

    val where_is_mir_fluff = listOf(
        VocabularyEntry(germanWords = listOf("belebt", "beschäftigt"), englishWords = listOf("busy")),
        VocabularyEntry(germanWords = listOf("für", "wen", "?"), englishWords = listOf("who... for?")),
        VocabularyEntry(germanWords = listOf("auf Entdeckungsreise gehen", "erkunden", "erforschen"), englishWords = listOf("to explore")),
        VocabularyEntry(germanWords = listOf("beste/r/s"), englishWords = listOf("best")),
        VocabularyEntry(germanWords = listOf("Tasche", "Tüte"), englishWords = listOf("bag")),
        VocabularyEntry(germanWords = listOf("vielleicht"), englishWords = listOf("maybe")),
        VocabularyEntry(germanWords = listOf("nach (zeitlich)"), englishWords = listOf("after")),
        VocabularyEntry(germanWords = listOf("Besuch"), englishWords = listOf("visit")),
        VocabularyEntry(germanWords = listOf("nach draußen", "draußen", "außerhalb (von)"), englishWords = listOf("outside")),
        VocabularyEntry(germanWords = listOf("schrecklich", "furchtbar"), englishWords = listOf("awful")),
        VocabularyEntry(germanWords = listOf("Keine Sorge"), englishWords = listOf("Don't worry")),
        VocabularyEntry(germanWords = listOf("Satz"), englishWords = listOf("sentence")),
        VocabularyEntry(germanWords = listOf("richtig", "korrekt"), englishWords = listOf("right")),
        VocabularyEntry(germanWords = listOf("Ende", "Schluss (Geschichte)"), englishWords = listOf("ending")),
        VocabularyEntry(germanWords = listOf("über etw. sprechen", "über etw. erzählen"), englishWords = listOf("to talk about")),
        VocabularyEntry(germanWords = listOf("Problem", "Schwierigkeit"), englishWords = listOf("problem")),
        VocabularyEntry(germanWords = listOf("das ist", "sind", "es gibt"), englishWords = listOf("there is", "there are")),
        VocabularyEntry(germanWords = listOf("da", "dort", "dahin", "dorthin"), englishWords = listOf("there")),
        VocabularyEntry(germanWords = listOf("Garten"), englishWords = listOf("garden")),
        VocabularyEntry(germanWords = listOf("hinter"), englishWords = listOf("behind")),
        VocabularyEntry(germanWords = listOf("Herr", "Anrede"), englishWords = listOf("Mr")),
        VocabularyEntry(germanWords = listOf("Frau", "Anrede"), englishWords = listOf("Mrs")),
        VocabularyEntry(germanWords = listOf("jetzt", "nun"), englishWords = listOf("now")),
        VocabularyEntry(germanWords = listOf("Auto"), englishWords = listOf("car")),
        VocabularyEntry(germanWords = listOf("überall", "überallhin"), englishWords = listOf("everywhere")),
        VocabularyEntry(germanWords = listOf("wieder", "noch einmal", "noch mal"), englishWords = listOf("again")),
        VocabularyEntry(germanWords = listOf("Fußboden"), englishWords = listOf("floor")),
        VocabularyEntry(germanWords = listOf("neben"), englishWords = listOf("next to")),
        VocabularyEntry(germanWords = listOf("vor"), englishWords = listOf("in front of")),
        VocabularyEntry(germanWords = listOf("zuhören", "anhören"), englishWords = listOf("listen", "listen to")),
        VocabularyEntry(germanWords = listOf("Idee", "Einfall"), englishWords = listOf("idea")),
        VocabularyEntry(germanWords = listOf("Dachboden"), englishWords = listOf("loft")),
        VocabularyEntry(germanWords = listOf("eigen"), englishWords = listOf("own")),
    )
    val combinedList = unit_1 + this_is_my_room +where_is_mir_fluff

    val allLists: Map<String, List<VocabularyEntry>> = mapOf(
        "Wiederholung (alle Vokabeln)" to combinedList,
        "Unit 1 - call " to unit_1,
        "This is my Room" to this_is_my_room,
        "Where is Mir fluff?" to where_is_mir_fluff,
        // Füge hier weitere Listen hinzu"
        // Füge hier weitere Listen hinzu, z.B. "Liste 3: Verben" to listThree
    )

    // Standardmäßig ausgewählte Liste oder null, wenn keine Vorauswahl getroffen werden soll
    var currentListName: String? = allLists.keys.firstOrNull() // Wählt die erste Liste als Standard

    fun getCurrentVocabularyList(): List<VocabularyEntry>? {
        return currentListName?.let { allLists[it] }
    }
}